### ISSUE TITLE
maim is ten times as slow as scrot.

### ISSUE THREAD

**Issue by crocket** [naelstrof/maim#100]
```
$ time scrot ok.png

real    0m0.525s
user    0m0.486s
sys     0m0.012s
```

```
$ time maim ok.png

real    0m5.289s
user    0m5.191s
sys     0m0.051s
```

```
$ file ok.png
ok.png: PNG image data, 3840 x 1080, 8-bit/color RGB, non-interlaced
```

It took 0.525 second for scrot and 5.289 seconds for maim.
Without compton, the time it takes to take a screenshot increases slightly for both maim and scrot.

**Comment by naelstrof** [comment]
It's because maim, by default, maximizes the png quality. (Reducing file sizes).
You're free to change the quality with the `-q` parameter.

All of my machines take a reasonable amount of time to compress the image, though I don't have a 4k display.

I'll think about reducing the default quality.

**Comment by crocket** [comment]
Did you maximize png compression level?

**Comment by naelstrof** [comment]
Yes. You can change it with the `-q` parameter.

**Comment by crocket** [comment]
According to my test, `-m 3` is a reasonable compromise.

**Comment by naelstrof** [comment]
Oh right, I forgot `-q` is the quiet parameter, going to edit my posts for that so people don't get confused.

**Comment by naelstrof** [comment]
I reduced the default quality to 7 in this commit: https://github.com/naelstrof/maim/commit/31bb900cb1639257d9d3709199a548bb5fdedf47

I won't lower it further than that, since most people won't notice the longer time. (Only those with abysmal CPUs or 4k monitors care, and that's why the option exists.)

**Comment by crocket** [comment]
Or, those with dual monitor setup. Another issue is lack of awareness of `-m` among users.
It doesn't take a genius to figure it out, but I wasn't aware of it when I submitted this issue.
Would user awareness be a worthy problem to solve?
