### ISSUE TITLE
There is no easy way to make maim capture the focused window.

### ISSUE THREAD

**Issue by crocket** [naelstrof/maim#101]
With scrot, I can just execute `scrot --focused filename.png`.
With maim, it seems I have to find a way to obtain the focused window by some other esoteric means.

**Comment by naelstrof** [comment]
Not a bug. Not going to implement.

**Comment by crocket** [comment]
It's not a bug, but not every problem is a bug.
We're problem solvers.
My problem is that it takes one keyboard shortcut and one mouse click to capture the focused window instead of just one keyboard shortcut.

This use case is commoner than `--select`.

I'd like to know why you are not going to implement it.

**Comment by crocket** [comment]
I now see that one of your examples combines maim with another program to capture the current window.
But, simply `Not a bug. Not going to implement` feels a bit rude. You could take more time to explain the rationale behind your decision to close this issue.

**Comment by naelstrof** [comment]
Yeah my bad, I was playing starcraft with some friends at the time. Glad you could figure it out, and sorry if I seemed abrasive.

**Comment by crocket** [comment]
Could your explain the rationale behind not implementing `--focused`?
Is it some sort of an undocumented design goal? Or?

**Comment by naelstrof** [comment]
Maim's philosophy is to do one thing, and to do it well. Bash already has the "--focused" functionality. There's no need to create redundancy.

You can easily create an alias if it bothers you too much.
```sh
alias maim-f="maim -i$(xdotool getactivewindow)"
