### ISSUE TITLE
cannot select non-root window

### ISSUE THREAD

**Issue by jebrosen** [naelstrof/maim#105]
In parseWindow with the new options parsing code ( https://github.com/naelstrof/maim/blob/ef4347d127f170a906db93a8129758da00c5fb8e/src/main.cpp#L69 ), retwin is assigned but never returned, so no window other than the root window can be selected.

Adding a 'return retwin' line seems to fix the problem.

**Comment by naelstrof** [comment]
Whoops! All of my tests just used "root" so I didn't notice anything wrong. It should be fixed now. Thanks!

**Comment by jebrosen** [comment]
Works for me now, thanks for responding so quickly!
