### ISSUE TITLE
Linking error in slop

### ISSUE THREAD

**Issue by DwijadasDey** [naelstrof/maim#108]
Hi
   I am trying to install maim in Ubuntu 16.10 . The make runs successfully but in $make install i got this error during [linking.](https://pastebin.com/T4EfCvL1)    I have already installed libicu-dev and libicu57 .
Like to know, if there is any environment variable that need to pass during $make, that would point to  libicu-dev/libicu57 

Regards

**Comment by naelstrof** [comment]
what's the output of `cmake ./`?
You probably want to do `cmake -DSLOP_UNICODE=true ./`, despite it being defaulted to true it seems like it isn't for you.

Read the CMakeLists.txt for more information.

**Comment by DwijadasDey** [comment]
Hi
    The output of is  cmake ./

root@ubuntu:~/slop# cmake ./
-- Configuring done
-- Generating done
-- Build files have been written to: /root/slop


The no of linking errors seems to be gone down after making changes to the cmake command to 
cmake -DSLOP_UNICODE=true ./

The errors are still [there.](https://pastebin.com/hZHEpppS)

Regards

**Comment by DwijadasDey** [comment]
The installation of slop is successful if i pass  -DSLOP_UNICODE=false to cmake.

root@ubuntu:~/slop# cmake -DCMAKE_INSTALL_PREFIX="/usr" -DSLOP_UNICODE=false ./
-- Configuring done
-- Generating done
-- Build files have been written to: /root/slop
root@ubuntu:~/slop# 
root@ubuntu:~/slop# 
root@ubuntu:~/slop# 
root@ubuntu:~/slop# 
root@ubuntu:~/slop# make && sudo make install
Scanning dependencies of target slopy
[  6%] Building CXX object CMakeFiles/slopy.dir/src/mouse.cpp.o
[ 12%] Building CXX object CMakeFiles/slopy.dir/src/gl_core_3_0.cpp.o
[ 18%] Building CXX object CMakeFiles/slopy.dir/src/keyboard.cpp.o
[ 25%] Building CXX object CMakeFiles/slopy.dir/src/x.cpp.o
[ 31%] Building CXX object CMakeFiles/slopy.dir/src/slopstates.cpp.o
[ 37%] Building CXX object CMakeFiles/slopy.dir/src/framebuffer.cpp.o
[ 43%] Building CXX object CMakeFiles/slopy.dir/src/resource.cpp.o
[ 50%] Building CXX object CMakeFiles/slopy.dir/src/shader.cpp.o
[ 56%] Building CXX object CMakeFiles/slopy.dir/src/window.cpp.o
[ 62%] Building CXX object CMakeFiles/slopy.dir/src/slop.cpp.o
[ 68%] Building CXX object CMakeFiles/slopy.dir/src/rectangle.cpp.o
[ 75%] Building CXX object CMakeFiles/slopy.dir/src/xshaperectangle.cpp.o
[ 81%] Building CXX object CMakeFiles/slopy.dir/src/glrectangle.cpp.o
[ 87%] Linking CXX shared library libslopy.so
[ 87%] Built target slopy
Scanning dependencies of target slop
[ 93%] Building CXX object CMakeFiles/slop.dir/src/main.cpp.o
[100%] Linking CXX executable bin/slop
[100%] Built target slop
[ 87%] Built target slopy
[100%] Built target slop
Install the project...
-- Install configuration: "Debug"
-- Installing: /usr/bin/slop
-- Set runtime path of "/usr/bin/slop" to ""
-- Installing: /usr/lib/libslopy.so
-- Installing: /usr/include/slop.hpp
-- Installing: /usr/share/man/man1/slop.1.gz

**Comment by naelstrof** [comment]
Installing the ICU libraries would solve this problem as well, only matters for people who want unicode support.
