### ISSUE TITLE
terminate called after throwing an instance of 'std::regex_error'

### ISSUE THREAD

**Issue by heelsleeh** [naelstrof/maim#109]
type  maim -s

maim v5.4.63
slop v6.3.38

**Comment by naelstrof** [comment]
Going to need some more information that that. `maim -s` doesn't segfault for me.
For compiling you might need to check out the requirements of the parser I'm using:
https://github.com/jarro2783/cxxopts#requirements

**Comment by naelstrof** [comment]
If you could run `valgrind maim -s` and give me the output that might be helpful.

**Comment by Redcroft** [comment]
Hi, i get the same problem (Centos 7.5)

`valgrind maim -s
==83247== Memcheck, a memory error detector
==83247== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==83247== Using Valgrind-3.13.0 and LibVEX; rerun with -h for copyright info
==83247== Command: maim -s
==83247==
terminate called after throwing an instance of 'std::regex_error'
  what():  regex_error
==83247==
==83247== Process terminating with default action of signal 6 (SIGABRT)
==83247==    at 0x74FD277: raise (in /usr/lib64/libc-2.17.so)
==83247==    by 0x74FE967: abort (in /usr/lib64/libc-2.17.so)
==83247==    by 0x6D087D4: __gnu_cxx::__verbose_terminate_handler() (in /usr/lib64/libstdc++.so.6.0.19)
==83247==    by 0x6D06745: ??? (in /usr/lib64/libstdc++.so.6.0.19)
==83247==    by 0x6D06772: std::terminate() (in /usr/lib64/libstdc++.so.6.0.19)
==83247==    by 0x6D06992: __cxa_throw (in /usr/lib64/libstdc++.so.6.0.19)
==83247==    by 0x6D5BDD4: std::__throw_regex_error(std::regex_constants::error_type) (in /usr/lib64/libstdc++.so.6.0.19)
==83247==    by 0x47A2D1: std::__detail::_Compiler<char const*, std::regex_traits<char> >::_M_bracket_expression() (regex_compiler.h:974)
==83247==    by 0x478863: std::__detail::_Compiler<char const*, std::regex_traits<char> >::_M_atom() (regex_compiler.h:960)
==83247==    by 0x476A28: std::__detail::_Compiler<char const*, std::regex_traits<char> >::_M_term() (regex_compiler.h:795)
==83247==    by 0x47421B: std::__detail::_Compiler<char const*, std::regex_traits<char> >::_M_alternative() (regex_compiler.h:773)
==83247==    by 0x471DAB: std::__detail::_Compiler<char const*, std::regex_traits<char> >::_M_disjunction() (regex_compiler.h:758)
==83247==
==83247== HEAP SUMMARY:
==83247==     in use at exit: 296,167 bytes in 85 blocks
==83247==   total heap usage: 1,078 allocs, 993 frees, 107,084,658 bytes allocated
==83247==
==83247== LEAK SUMMARY:
==83247==    definitely lost: 0 bytes in 0 blocks
==83247==    indirectly lost: 0 bytes in 0 blocks
==83247==      possibly lost: 287,847 bytes in 4 blocks
==83247==    still reachable: 8,320 bytes in 81 blocks
==83247==                       of which reachable via heuristic:
==83247==                         stdstring          : 88 bytes in 3 blocks
==83247==         suppressed: 0 bytes in 0 blocks
==83247== Rerun with --leak-check=full to see details of leaked memory
==83247==
==83247== For counts of detected and suppressed errors, rerun with: -v
==83247== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
Aborted (core dumped)
`

Thanks

**Comment by heelsleeh** [comment]
yes, gcc-4.8 problem, thanks all.
