### ISSUE TITLE
Send notification when screenshot taken

### ISSUE THREAD

**Issue by ecly** [naelstrof/maim#110]
Is it currently possible, or could it possibly be added, to allow for sending a notification with eg. screenshot name and location upon taking a screen. Seems possible with a script but would be a nice integration.

**Comment by naelstrof** [comment]
Yeah sorry, that's easily implemented with a script. So I don't plan on implementing it as a feature.
Here's an example script. (I didn't test it, but the concept should be pretty clear).

```sh
#!/bin/bash
NAME=~/Pictures/$(date +%s).png
maim -s $(NAME)
notify-send 'Picture taken!' "It was saved at $(NAME)" --icon=camera-photo
```

**Comment by ecly** [comment]
Alright - no problem. Thanks a lot!
