### ISSUE TITLE
Black square on the center of the screen

### ISSUE THREAD

**Issue by Lonami** [naelstrof/maim#114]
After some discussion in a Telegram group, we think it probably is the feature that masks off-screen pixels to be transparent or black. However, this masking is always happening on the center of the screen for some reason:
<table><tr><td><img src="https://user-images.githubusercontent.com/6297805/30373397-7b6697ce-9881-11e7-889a-07dbf4665008.png" /></td></tr></table>

Laptop screen, 1366x768 resolution, Arch Linux.

<details><summary>Output from <code>lspci -v</code> (click to expand)</summary>
<pre>
00:00.0 Host bridge: Intel Corporation Broadwell-U Host Bridge -OPI (rev 09)
	Subsystem: ASUSTeK Computer Inc. Device 19ad
	Flags: bus master, fast devsel, latency 0
	Capabilities: <access denied>
	Kernel driver in use: bdw_uncore
lspci: Unable to load libkmod resources: error -12

00:02.0 VGA compatible controller: Intel Corporation HD Graphics 5500 (rev 09) (prog-if 00 [VGA controller])
	Subsystem: ASUSTeK Computer Inc. Device 19ad
	Flags: bus master, fast devsel, latency 0, IRQ 49
	Memory at b1000000 (64-bit, non-prefetchable) [size=16M]
	Memory at c0000000 (64-bit, prefetchable) [size=256M]
	I/O ports at 4000 [size=64]
	[virtual] Expansion ROM at 000c0000 [disabled] [size=128K]
	Capabilities: <access denied>
	Kernel driver in use: i915

00:03.0 Audio device: Intel Corporation Broadwell-U Audio Controller (rev 09)
	Subsystem: ASUSTeK Computer Inc. Device 19ad
	Flags: bus master, fast devsel, latency 0, IRQ 50
	Memory at b221c000 (64-bit, non-prefetchable) [size=16K]
	Capabilities: <access denied>
	Kernel driver in use: snd_hda_intel

00:04.0 Signal processing controller: Intel Corporation Broadwell-U Processor Thermal Subsystem (rev 09)
	Subsystem: ASUSTeK Computer Inc. Device 19ad
	Flags: bus master, fast devsel, latency 0, IRQ 16
	Memory at b2210000 (64-bit, non-prefetchable) [size=32K]
	Capabilities: <access denied>
	Kernel driver in use: proc_thermal

00:14.0 USB controller: Intel Corporation Wildcat Point-LP USB xHCI Controller (rev 03) (prog-if 30 [XHCI])
	Subsystem: ASUSTeK Computer Inc. Device 201f
	Flags: bus master, medium devsel, latency 0, IRQ 45
	Memory at b2200000 (64-bit, non-prefetchable) [size=64K]
	Capabilities: <access denied>
	Kernel driver in use: xhci_hcd

00:16.0 Communication controller: Intel Corporation Wildcat Point-LP MEI Controller #1 (rev 03)
	Subsystem: ASUSTeK Computer Inc. Device 19ad
	Flags: bus master, fast devsel, latency 0, IRQ 48
	Memory at b2224000 (64-bit, non-prefetchable) [size=32]
	Capabilities: <access denied>
	Kernel driver in use: mei_me

00:1b.0 Audio device: Intel Corporation Wildcat Point-LP High Definition Audio Controller (rev 03)
	Subsystem: ASUSTeK Computer Inc. Device 19ad
	Flags: bus master, fast devsel, latency 32, IRQ 47
	Memory at b2218000 (64-bit, non-prefetchable) [size=16K]
	Capabilities: <access denied>
	Kernel driver in use: snd_hda_intel

00:1c.0 PCI bridge: Intel Corporation Wildcat Point-LP PCI Express Root Port #1 (rev e3) (prog-if 00 [Normal decode])
	Flags: bus master, fast devsel, latency 0, IRQ 42
	Bus: primary=00, secondary=01, subordinate=01, sec-latency=0
	I/O behind bridge: None
	Memory behind bridge: None
	Prefetchable memory behind bridge: None
	Capabilities: <access denied>
	Kernel driver in use: pcieport

00:1c.2 PCI bridge: Intel Corporation Wildcat Point-LP PCI Express Root Port #3 (rev e3) (prog-if 00 [Normal decode])
	Flags: bus master, fast devsel, latency 0, IRQ 43
	Bus: primary=00, secondary=02, subordinate=02, sec-latency=0
	I/O behind bridge: 00003000-00003fff [size=4K]
	Memory behind bridge: b2100000-b21fffff [size=1M]
	Prefetchable memory behind bridge: None
	Capabilities: <access denied>
	Kernel driver in use: pcieport

00:1c.3 PCI bridge: Intel Corporation Wildcat Point-LP PCI Express Root Port #4 (rev e3) (prog-if 00 [Normal decode])
	Flags: bus master, fast devsel, latency 0, IRQ 44
	Bus: primary=00, secondary=03, subordinate=03, sec-latency=0
	I/O behind bridge: None
	Memory behind bridge: b2000000-b20fffff [size=1M]
	Prefetchable memory behind bridge: None
	Capabilities: <access denied>
	Kernel driver in use: pcieport

00:1f.0 ISA bridge: Intel Corporation Wildcat Point-LP LPC Controller (rev 03)
	Subsystem: ASUSTeK Computer Inc. Device 19ad
	Flags: bus master, medium devsel, latency 0
	Capabilities: <access denied>
	Kernel driver in use: lpc_ich

00:1f.2 SATA controller: Intel Corporation Wildcat Point-LP SATA Controller [AHCI Mode] (rev 03) (prog-if 01 [AHCI 1.0])
	Subsystem: ASUSTeK Computer Inc. Device 19ad
	Flags: bus master, 66MHz, medium devsel, latency 0, IRQ 46
	I/O ports at 40b0 [size=8]
	I/O ports at 40a0 [size=4]
	I/O ports at 4090 [size=8]
	I/O ports at 4080 [size=4]
	I/O ports at 4060 [size=32]
	Memory at b2222000 (32-bit, non-prefetchable) [size=2K]
	Capabilities: <access denied>
	Kernel driver in use: ahci

00:1f.3 SMBus: Intel Corporation Wildcat Point-LP SMBus Controller (rev 03)
	Subsystem: ASUSTeK Computer Inc. Device 19ad
	Flags: medium devsel, IRQ 22
	Memory at b2221000 (64-bit, non-prefetchable) [size=256]
	I/O ports at 4040 [size=32]
	Kernel driver in use: i801_smbus

00:1f.6 Signal processing controller: Intel Corporation Wildcat Point-LP Thermal Management Controller (rev 03)
	Subsystem: ASUSTeK Computer Inc. Device 19ad
	Flags: bus master, fast devsel, latency 0, IRQ 22
	Memory at b2220000 (64-bit, non-prefetchable) [size=4K]
	Capabilities: <access denied>
	Kernel driver in use: intel_pch_thermal

02:00.0 Ethernet controller: Realtek Semiconductor Co., Ltd. RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller (rev 10)
	Subsystem: ASUSTeK Computer Inc. Device 200f
	Flags: bus master, fast devsel, latency 0, IRQ 51
	I/O ports at 3000 [size=256]
	Memory at b2104000 (64-bit, non-prefetchable) [size=4K]
	Memory at b2100000 (64-bit, non-prefetchable) [size=16K]
	Capabilities: <access denied>
	Kernel driver in use: r8169

03:00.0 Network controller: Qualcomm Atheros QCA9565 / AR9565 Wireless Network Adapter (rev 01)
	Subsystem: AzureWave Device 213a
	Flags: bus master, fast devsel, latency 0, IRQ 19
	Memory at b2000000 (64-bit, non-prefetchable) [size=512K]
	Expansion ROM at b2080000 [disabled] [size=64K]
	Capabilities: <access denied>
	Kernel driver in use: ath9k
</pre></details>

<details><summary>Output from <code>xrandr -q</code> (click to expand)</summary>
<pre>
Screen 0: minimum 8 x 8, current 1366 x 768, maximum 32767 x 32767
eDP1 connected 1366x768+0+0 (normal left inverted right x axis y axis) 340mm x 190mm
   1366x768      60.00*+
   1280x720      60.00  
   1024x768      60.00  
   1024x576      60.00  
   960x540       60.00  
   800x600       60.32    56.25  
   864x486       60.00  
   640x480       59.94  
   720x405       60.00  
   680x384       60.00  
   640x360       60.00  
DP1 disconnected (normal left inverted right x axis y axis)
HDMI1 disconnected (normal left inverted right x axis y axis)
HDMI2 disconnected (normal left inverted right x axis y axis)
VIRTUAL1 disconnected (normal left inverted right x axis y axis)
</pre></details>

**Comment by naelstrof** [comment]
It definitely isn't the masking. I haven't seen a problem like this before though.
What maim command are you using? Have you tried disabling/enabling the mouse overlay option?
Does your system have XRender/XFixes support? ([getImageUsingXRender vs XGetImage](https://github.com/naelstrof/maim/blob/master/src/x.cpp#L164))
Which version of maim are you using?
Does screenshotting the root window `maim -i root` do anything different compared to drag selecting or clicking on a specific window?

**Comment by Lonami** [comment]
> What maim command are you using?

All these commands make the effect show:
```
$ maim > maim.png
$ maim -s > maim-s.png
$ maim -u > maim-u.png
$ maim -s -u > maim-s-u.png
```

<details><summary>Show screenshots (the alpha shows GitHub's white background and you can't see it from here)</summary>
<img src="https://user-images.githubusercontent.com/6297805/30393190-941823da-98bf-11e7-86d3-8f288db6ee30.png" />
<img src="https://user-images.githubusercontent.com/6297805/30393191-95ac32e0-98bf-11e7-9cae-dc3d36cd365c.png" />
<img src="https://user-images.githubusercontent.com/6297805/30393193-9861ba8c-98bf-11e7-84e2-5bbb8f34d524.png" />
<img src="https://user-images.githubusercontent.com/6297805/30393196-996c898e-98bf-11e7-92ab-8ba01b6e78f7.png" />
</details>

---

> Have you tried disabling/enabling the mouse overlay option?

Yes

> Which version of maim are you using?

v5.4.66

> Does screenshotting the root window `maim -i root` do anything different compared to clicking on a specific window?

Same transparent square. Although a second test clicking the window with `-s` actually displaced the box (as `.jpg` to show it):
![image](https://user-images.githubusercontent.com/6297805/30393375-2ae35da2-98c0-11e7-87d1-2766c978130b.png)

**Comment by naelstrof** [comment]
Upgrade maim, this bug is fixed in v5.4.68.

**Comment by Lonami** [comment]
Okay, sorry for the trouble! `pacaur` only shows `maim-5.4.66-1` so I may just compile it on my own.

**Comment by naelstrof** [comment]
maim is actually found in community, which is currently out of date as of August. You can send complaints to Lukas Fleischer here: https://www.archlinux.org/packages/community/x86_64/maim/
Otherwise you can install maim-git, and slop-git from the AUR which will always be up-to-date.

**Comment by Lonami** [comment]
Building it is dead simple (which I appreciate), so I just did that. Thanks again and sorry to bother.
