### ISSUE TITLE
Broken screenshot of hardware accelerated areas

### ISSUE THREAD

**Issue by gogoprog** [naelstrof/maim#116]
Hello,

It used to work but since a few weeks I cannot take screenshots of OpenGL apps, Chrome, Firefox, etc. anymore...

```
maim: v5.4.66
os: ArchLinux
wm: AwesomeWM v4.2
```

The taken screenshots look like this:
![2017-10-11_20 46 44](https://user-images.githubusercontent.com/1249453/31460259-1547f1d0-aec6-11e7-8c67-ed4fd833924d.png)
or entirely white.

Is this a known issue?

**Comment by naelstrof** [comment]
Update maim.

**Comment by gogoprog** [comment]
Thanks
