### ISSUE TITLE
maim equivalent to scrot -e  ?

### ISSUE THREAD

**Issue by JarrColl** [naelstrof/maim#118]
I want to do a maim -s save the image to /tmp/ then open the image in feh

**Comment by Sweenu** [comment]
The neat feature of maim is that it outputs the file to standard output by default. So you can just do `maim | feh` to open it in feh .

If you really want to save it in /tmp/, here's what you can do: `maim | tee /tmp/$(date +%s) | feh`

**Comment by naelstrof** [comment]
It's actually `maim | feh -` to open it in feh. To save in tmp, then open in feh you'd do `maim | tee /tmp$(date +%s) | feh -`.
The - is important to tell feh to open from standard input.

**Comment by naelstrof** [comment]
It does work with the -s tag, you just forgot the - after feh. `maim -s |
feh -` would be the correct command. A solitary - indicates for a program
to read from standard input.

**Comment by JarrColl** [comment]
ah thank you
