### ISSUE TITLE
-g (geometry) switch not working as documented

### ISSUE THREAD

**Issue by CyberShadow** [naelstrof/maim#119]
From `man maim`:

> So -g10x30-5+0 would represent the rectangle wxh+x+y where w=10, h=30, x=-5, and y=0. x and y are the upper left location of this rectangle.

However, running `maim -g10x30-5+0 a.png` instead creates the *file* `-g10x30-5+0`.

`maim` also does not complain about the additional `a.png` argument it apparently ignores.

`maim --version` is `v5.4.68`.

**Comment by jakkn** [comment]
Can confirm
```
~/Pictures $ maim -v
v5.4.68
~/Pictures $ maim --geometry=10x30-10+10 ~/Pictures/foo.jpg 
~/Pictures $ ls
foo.jpg
~/Pictures $ maim -g10x30-10+10 ~/Pictures/foo.jpg 
~/Pictures $ ls
foo.jpg  -g10x30-10+10
```
But it works if you add a space between the switch and the argument like so
```
~/Pictures $ rm *
~/Pictures $ ls
~/Pictures $ maim -g 10x30-10+10 ~/Pictures/foo.jpg 
~/Pictures $ ls
foo.jpg
```
