### ISSUE TITLE
Custom picker color

### ISSUE THREAD

**Issue by koxu1996** [naelstrof/maim#123]
Currently area picker is grey and totally invisible in my terminal. What about adding option to customize it?

**Comment by naelstrof** [comment]
Try the --color option, check out https://github.com/naelstrof/slop for more customization options.

**Comment by koxu1996** [comment]
Ah, it's related to slop. Sorry for bothering you and thanks for help.

**Comment by naelstrof** [comment]
No problem! Maim supports anything that slop does, unless the option names conflict. In which case it just uses a different option.
