### ISSUE TITLE
Maim captures slop shader

### ISSUE THREAD

**Issue by FliiFe** [naelstrof/maim#130]
Here is an example of what maim captures:
![res](https://user-images.githubusercontent.com/8740385/36947737-4a38293e-1fd0-11e8-9dca-3aa1a5c8736a.png)

The issue here is that maim doesn't wait for the slop shader to disappear before taking a screenshot.
This time is due to my compositor (`compton`), which animates the opening and closing of windows.

I suggest either finding a way of finding out wether slop has disappeared (I don't think that is possible, since the animation is made by the compositor, after slop has exited), or adding a switch to delay the screenshot taking process.

Either way, here is a temporary fix:
```bash
#!/usr/bin/env bash

geometry=$(slop)
sleep 1
maim $@ -g $geo
```

**Comment by naelstrof** [comment]
You can add slop to the exception list in Compton also.

**Comment by raku-cat** [comment]
> or adding a switch to delay the screenshot taking process.

This already exists, `-d` or `--delay`.

**Comment by FliiFe** [comment]
I think this can be closed, everything necessary has been mentioned.

**Comment by krigstask** [comment]
> This already exists, -d or --delay.

Would that help in that case?  I would imagine that it add delay *before* taking screenshot (to give user some time to prepare screen), not after it (as I think is required in this particular case).

**Comment by raku-cat** [comment]
Would it help? I'm not sure, I just pointed out the existence of the flag. From what I'm seeing though this appears to be resolved regardless.

**Comment by fwookerton** [comment]
Good command but I think there should be a "blur-exclude" that disables blur entirely from some programs. I've included "dunst" to "blur-background-exclude" and it doesn't really remove the blur. When it fades in, you can see the blur and it honestly looks kinda ugly.
