### ISSUE TITLE
Capture data to terminal console not to file

### ISSUE THREAD

**Issue by Ygarr** [naelstrof/maim#137]
While making screenshot I got the following. How to save to file by default(without redirection)?
System Debian Sid. 
Linux Sabayon and ArchLinux works fine

maim -s
Failed to detect a compositor, OpenGL hardware-accelleration disabled...
�PNG

IHDR�	��m�IDATx��ܿq�F�=��A�\C�E��e'J]�]�\:�8cl'.�=(T�8ρ���>�
                                                                          ����K,V�����f_��{v��C�!��a��!�;�!�B�!��a��!�;�!�B�!��C�Aa������?�>׾3�d�;��,d�*�����?>�{}����a}s{ಞ��%���R�qWx��m����d���
�s���������C�g�	�c����0�ǿ��!�B�!��a�O������߼wt�����\����T���8��?���d������`fO¾�@�y�n�����M����g
         ��5�94���Wې�����}�����i���j�?���y
                                           C������ؾ��1�l߆.��V<�����W���{���;�Nsݮ�����i�~�y��D��k[g̶mp_}��|l�[pս�:�}�h�kh�C֯~����r���g��
                         [�!���ϓu펝���c�o.�da���	äK��������񡚵��-\��ԏ�����#C���zk������?6	Զ|�Los�X}����c����,�Б�-b�O�!�a<��d��!Գ�$������q��!�z�3�z=���/ǩgW�~p�S����;���j���=t�������g�C�;��}��z�t}v�z�-�ӫg_�5׳Oai�o��$��Wb���S�=��m�z�A=�F��ߤc=�">T��S=����ӫg�@�K�gs|]����S���°J�ml��~�x`~���7�-῍��a<�0���!Գ�$��}����z�����^�>֥��֩gW�~p�!噇Lu}��P�>�z������z���O���I�Wﲙլ}rg���K�>��
Գo��K�E|�f-7�z�eK�W}�/��}h�M��>[�W���x[�Wﲈa<0?a���;�8�o���|��ϓw6W�@7O��]�����_/�C�<:?�6���28�N��E}��mm��d��^����
          o�����;��MR�&��|�a?�]��v��c6B<+�
                                            <$�d�O���L����p~
a �w!�B�!��a��!�;�!�B�!��a��!�;�!�B�!��a��!�;�!�B�!��a��!�;�!�B�!��a��!�;�!�B�!��a��!�;�!�B�!��a��!�;�!�B�!��a��!�;�!�B�!��a��!�;�!�B�!��a��!�;���������˄6�|a���B^���������~_��Ã���ԃ^����իRʁ���������s���=wp)����ߗ�/_>.{��a���j����ʋ/ʟ��_�ooo�۷o;���)�j��y���
��;��Ah{Z6�k�׶�k���:iv�]y�����]�����Mе=��՗7�=����`k��������Ǐ���u�����f��/���v������ϟˇ�7�_���'��m��W=٫?W_�(��ͪ�K����-@y�4�?������͌����[�Ϲ~��y|�D���R���榽&X��g�������]yu}�����tvظ*���n:L�2��IEND�B`�

**Comment by naelstrof** [comment]
`maim -s hello.png` would save it to hello.png in your current directory.

**Comment by Ygarr** [comment]
By the way I did alias or symlink  --- 
maim  $(date +"%Y_%m_%d_%I_%M_%p_%s").png -s
