### ISSUE TITLE
Cursor not showing

### ISSUE THREAD

**Issue by AUTplayed** [naelstrof/maim#138]
As you can see in the video my cursor isn't shown in the screenshot.

https://i.imgur.com/pEzUh3V.mp4

I'm using manjaro + i3-gaps with maim v5.4.68

**Comment by raku-cat** [comment]
How do you expect it to see your cursor? You're selecting an area, and then it's grabbing that area. If you want your cursor to show up in the screenshot you need to add a delay, this works fine for me 
![image](https://user-images.githubusercontent.com/1125449/39965174-b9f943ba-5659-11e8-8fd0-08eb8e4e6c2f.png)
