### ISSUE TITLE
Activating maim selection mode causes black screen

### ISSUE THREAD

**Issue by euclio** [naelstrof/maim#141]
OS: Arch Linux
WM: XMonad
Version: 5.4.68
Command: `maim -s`

Entering selection mode causes both of my monitors to go black. I can still see the selection cursor, and actually selecting a region will create the correct screenshot, but it makes it impossible to actually select anything visually. Cancelling maim causes the screens to return to normal.

Please let me know if I can provide additional debugging information.

**Comment by naelstrof** [comment]
Try the --noopengl flag, see if that fixes it.

**Comment by euclio** [comment]
Yeah, that did it! Thanks.
