### ISSUE TITLE
Where does maim save?

### ISSUE THREAD

**Issue by acgtyrant** [naelstrof/maim#142]
I execute `main -s` in dmenu, but there is not any results like `2018-05-16-110139_1919x1053_scrot.png` in my $HOME.

`scrot -s` will save result in $HOME like `2018-05-16-110139_1919x1053_scrot.png ` when I do not  specify the save position.

**Comment by naelstrof** [comment]
You can alias maim to do so, but by default maim outputs directly to the console. The readme explains in more detail, and I don't plan on adding that functionality since I'd have to make assumptions like the user running the app has a home, and that they want a png saved there.
