### ISSUE TITLE
version check crashes when no DISPLAY present

### ISSUE THREAD

**Issue by issmirnov** [naelstrof/maim#143]
I'm writing an ansible playbook for automating my ubuntu deployment. As part of that script I'm checking the version of `maim` to see if it needs an update. However, running `maim --version` fails to return a version.

IMO, the version should be printed regardless of `DISPLAY` being set. If this is a small fix, could you squeeze it in? It'll help a lot with scripted installs.

```
$ maim -v
Maim encountered an error:
Error: Failed to open X display: :0
```

System: Ubuntu 16.04
Desktop Env: i3wm
Xorg: X.Org X Server 1.18.4

**Comment by naelstrof** [comment]
Yeah that's totally possible, if you were to make a pull request, I'll merge it. I'm at work at the moment so I can't fix it at the moment.
