### ISSUE TITLE
maim spamming gibberish and requests new fonts

### ISSUE THREAD

**Issue by predme** [naelstrof/maim#148]
I've used slop + maim before on Arch but after switching to Fedora, I'm having issues. I got slop and libslopy-devel from the repos and I built maim from source. Slop works fine and gives me the dimensions of my selections. Using main however is much more cryptic. It spams out this:

``u       ���%D:B�x�G�5���E@&�ٳ��n�=jê��\����ݳ�$EFp�D��7�OŶm���ϖv��H��K�����eeb;�����2��O��WJ/��!C�&~��
                               �.#���F���������H���T�
                                                         �'��L������R�[Pk�0�k�pj�r�	ǢB2pAo��j�$Y��Y(�D�P	�/�w�ńj���"ir7�߸���CX�1*]��	�S�[X��3%h&�������� %�܋�5ad��?��|�E02�I]���t>�7�:�*������,�>�)%���e��� ���C�0bΈ�>Ih�<3��7���C�-ۿ�wg��[�����5.��Ƥ�ʻT��PDn���Kw�_wXy.�``

It fills up my entire terminal to the point I can't scroll past it. There are no screenshots taken. I also get a notification that says "Additional Fonts Required. Terminal is requesting additional fonts.".

I currently use gnome-terminal but I've also tried terminator, both has issues with maim. My shell is fish but I've also tried maim with bash, same result. Like mentioned above, I'm also on Fedora and I'm using GNOME on X11. Any ideas?

**Comment by naelstrof** [comment]
That's intended. Maim outputs a full image to stdout. You should pipe it to a file, or give maim a filepath parameter.

**Comment by predme** [comment]
Oh, now I feel silly. Easy to lose track of how a program works when it's only used in scripts haha.
