### ISSUE TITLE
Don't set CMAKE_BUILD_TYPE if unset

### ISSUE THREAD

**Issue by Earnestly** [naelstrof/maim#168]
If `CMAKE_BUILD_TYPE` is unset cmake will fall back to the `None` build type which correctly uses environment variables such as `CFLAGS`, `CPPFLAGS`, etc.  Several distributions use this feature to preserve various policies on general purpose flags and such, i.e. https://lists.archlinux.org/pipermail/arch-dev-public/2018-March/029181.html

Currently to work around this I'm using `-DCMAKE_BUILD_TYPE=None` explicitly.

**Comment by foxpy** [comment]
I feel bad for this issue still laying around unnoticed. After almost three years of ignorance, I have checked out [here](https://github.com/archlinux/svntogit-community/blob/packages/maim/trunk/PKGBUILD), maim is built as is in Archlinux without using `-DCMAKE_BUILD_TYPE=None`.

@Earnestly is this issue still relevant? If it is, should we not set `CMAKE_BUILD_TYPE` to `Debug` so build system catches Archlinux's `CFLAGS`? (Also feels like a waste to build a non optimized binary, as I see that's what's happening now).

**Comment by Earnestly** [comment]
It is likely a packaging mistake if `CMAKE_BUILD_TYPE=None` is not set, however there are situations where it's not possible, see
https://wiki.archlinux.org/title/CMake_package_guidelines#Fixing_the_automatic_optimization_flag_override

Besides this I'll have to find some time to test maim specifically to see what it needs.

PS: No worries about old issues, so long as they remain open instead of being auto-closed after reaching some age limit.

**Comment by foxpy** [comment]
> Besides this I'll have to find some time to test maim specifically to see what it needs.

I don't see anything weird in maim's CMakeLists.txt which could cause troubles, **but** I did not test anything.

I have a plenty of time to do some testing, what should exactly be tested? I have never put any serious effort to package software properly (just smashing stuff until it works and that's it) so this question is more important than it may seem to be.

**Comment by Earnestly** [comment]
I would use `VERBOSE=1` with `make` and make sure it gets the right flags as defined in `/etc/makepkg.conf`.  This is usually good enough.

**Comment by foxpy** [comment]
And yeah, all the flags from `/etc/makepkg.conf` get included into build process as they should, no matter if I use Debug or None build type.

**Comment by Earnestly** [comment]
True, this situation is odd and contradicts the current understanding of cmake according to Arch.  If cmake has changed then it may just have to be updated.  Other than that it's probably fine to close this issue if you'd like.

**Comment by foxpy** [comment]
Another little experiment I made with cmake in an empty project: when I do `export CFLAGS="-static -Os"` and then do `cmake -DCMAKE_BUILD_TYPE=Release`, then compiler invocation looks like this: `/usr/bin/cc   -static -Os -O3 -DNDEBUG -MD -MT CMakeFiles/main.dir/main.c.o -MF CMakeFiles/main.dir/main.c.o.d -o CMakeFiles/main.dir/main.c.o -c /home/foxpy/cmake-test/main.c`.

**Takeaway §1**: if some day cmake developers decide to add something like `-Og` to default set of flags for Debug build type, in maim Arch package we will have a sequence of `$ARCH_CFLAGS -Og`, that doesn't sound good at all, our `-O2` will be replaced by `-Og`.

**Takeaway §2**: cmake makes it impossible to make reproducible builds without freezing cmake version.

**Comment by foxpy** [comment]
> it's probably fine to close this issue if you'd like

I have no idea what to do with issue at this point, because, even if we stick to None build type in maim, some day Kitware may screw us over by changing default cmake behaviour :)

**Comment by foxpy** [comment]
They say [here](https://cmake.org/cmake/help/v3.21/envvar/CFLAGS.html?highlight=cflags) that `CFLAGS` is always obtained on first run of cmake configuration process. They also say [here](https://cmake.org/cmake/help/v3.21/variable/CMAKE_LANG_FLAGS.html#variable:CMAKE_%3CLANG%3E_FLAGS) that it will be used regardless of `CMAKE_BUILD_TYPE`.

I have also tested it with cmake 3.5 on my VPS with some ancient Ubuntu and I have experienced the same behaviour.
It is probably not cmake changing over time, but Arch instructions being incorrect?

**Comment by Earnestly** [comment]
I'd suggest that you should stick with the defaults cmake provides and only change what you think is necessary.  Kitware changing things under your feet is inevitable but by staying default it allows for easier fixes or adjustments than trying to untangle some kind of custom feature set.

It also may very well be Arch being incorrect for sure

**Comment by foxpy** [comment]
So, now we are as close to defaults as possible, hope we wouldn't have any issues in future.
