### ISSUE TITLE
Window screenshots include i3 window borders

### ISSUE THREAD

**Issue by Caagr98** [naelstrof/maim#169]
Taking a screenshot of a tiled or floating window using i3wm includes a few pixels of the window border at the sides and bottom (not the top though). An example:

![xeyes with unwanted border](https://user-images.githubusercontent.com/1547062/53662440-316a7500-3c63-11e9-97fb-88879d2948e3.png)

(Don't mind the broken pixels, they're there in the real one.)

**Comment by naelstrof** [comment]
Are you using the -n option?

**Comment by Caagr98** [comment]
Turns out I wasn't. It worked. Thanks. (And boy, that was a fast response)
