### ISSUE TITLE
maim -s dark screen filter

### ISSUE THREAD

**Issue by lucascvassalli** [naelstrof/maim#171]
Same filter is present when I run slop. It shouldn't be on the resulted screenshot.
Q4OS 2.7, installed both slop and maim from APT, no changes to configuration.
[Image](https://i.imgtc.com/IYOIyJn.png)

**Comment by naelstrof** [comment]
You gotta add "slop" type windows to the ignore list to compton.

You can see a thread here about it: https://github.com/naelstrof/maim/issues/54

**Comment by lucascvassalli** [comment]
Thank you! Appending this https://github.com/naelstrof/maim/issues/40#issuecomment-126933853
to ~/.compton-tde.conf solved it.
