### ISSUE TITLE
screen blurs when taking shot

### ISSUE THREAD

**Issue by TheContortion1st** [naelstrof/maim#172]
Hi, 

when I take a selective screenshot (-s) the screen blurs and so the screenshot is blurred as well. 
![1553596066](https://user-images.githubusercontent.com/48633992/54990471-1e756700-4fbb-11e9-9cbb-263706ef4f99.png)

When I take a normal screenshot (w/o any option) it is crystal clear and with correct resolution. 
Any idea, what could cause this?
![blub](https://user-images.githubusercontent.com/48633992/54990487-26cda200-4fbb-11e9-8c5f-f7ec7914792c.png)

I'm using a Laptop with shut lid (1920x1080) working at a 27" monitor (2560x1440), configured via arand/xrandr in i3, if that's of any relevance. 

`exec_always --no-startup-id xrandr --output eDP-1 --off --output DP-1-2 --primary --mode 2560x1440 --pos 1920x0 --rotate normal --output HDMI-3 --off --output HDMI-2 --off --output HDMI-1 --off --output DP-1-1 --off --output DP-1-3 --off --output DP-2 --off --output DP-1 --off`

**Comment by TheContortion1st** [comment]
I found a solution (workaround?). With the -o option, to not use hardware acceleration, maim does not blur the screen and the shots are crystal clear. It's quite strange though, that the full screen default maim screenshot is normal as well and only the selective option blurs it.

**Comment by tdehaeze** [comment]
Same problem here with i3

**Comment by Haagen-Dazs** [comment]
Disabling blur in `compton` is another workaround.

**Comment by asuperpower** [comment]
Yeah, I'm having this issue as well (i3 + compton). Only happened when I turned blur on with compton and `maim -o` fixes the issue.

**Comment by JPUnD** [comment]
Having the same issue running i3 + compton on Manjaro, and i can confirm that using the -o flag on my system does in fact remove the blurring.

If i had to guess, i think i3 is somehow acting as if main -s were a window and as such blurs the background.

**Comment by garlifs** [comment]
This happens because of the compositor's blur effect. If you're using compton, you can add an exclusion for slop in your config without disabling hardware acceleration:
```
blur-background-exclude = [
    "class_g = 'slop'"
];
```

**Comment by krompus** [comment]
Similar/related issue, not sure if I should submit a new one. I just switched to picom-tryone, using a lightly modified [default/sample config](https://github.com/tryone144/picom/blob/feature/dual_kawase/picom.sample.conf) until I dive further into it. Whenever I go into selection mode `-s`, all of my displays dim a considerable amount. 

I've just added `"10:class_g = 'slop'",` within `opacity-rule = [`  as a workaround, but this still dims the images slightly. I'd love to know how to make it fully transparent again with the selection box still visible.

**Comment by j-james** [comment]
Tangentally, if anyone knows how to make picom's blur effect only happen outside of the selection box, let me know.

**Comment by jeanlucthumm** [comment]
I was able to solve the dimming issue. Turns out it's not related to opacity, it's related to shadows, so add an exclusion to shadows for `slop`:

```
shadow-exclude = [
  "class_g *?= 'slop'"
];
```

**Comment by polm** [comment]
@jeanlucthumm Thank you, that fixed dimming with picom for me!

**Comment by foxpy** [comment]
should this issue be closed now?

**Comment by Tanishq-Banyal** [comment]
i have same issue with `xfce4-screenshooter`,  tried adding it to blur exclusions but still blurring the selective screenshot overlay. Anyone knows the proper exclusion name for xfce4-screenshooter ?

**Comment by foxpy** [comment]
> i have same issue with `xfce4-screenshooter`, tried adding it to blur exclusions but still blurring the selective screenshot overlay. Anyone knows the proper exclusion name for xfce4-screenshooter ?

I have no idea about the "select region" widget itself, but maybe you could try something from main screenshooter window information:
```json
        {
            "border": "none",
            "current_border_width": 2,
            "floating": "user_off",
            "geometry": {
               "height": 318,
               "width": 545,
               "x": 410,
               "y": 225
            },
            "marks": [],
            "name": "Screenshot",
            "percent": 0.333333333333333,
            "swallows": [
               {
               "class": "^Xfce4\\-screenshooter$",
               "instance": "^xfce4\\-screenshooter$",
               "title": "^Screenshot$"
               }
            ],
            "type": "con"
        }
```

**Comment by SirJager** [comment]
blur-background-exclude = [
  "window_type = 'dock'",
  "window_type = 'desktop'",
  "class_g ?= 'xfce4-screenshooter'",
  "_GTK_FRAME_EXTENTS@:c"
];

  "class_g ?= 'xfce4-screenshooter'", # adding this line fixed issue (picom  | arch)

**Comment by foxpy** [comment]
I am closing this issue since all workarounds^Wsolutions have been researched. Feel free to open it again if you still have any problems.

**Comment by HanslettTheDev** [comment]
If you encoutered this same issue, for anyone here in 2026, the comment from the **ghost** user who has been deleted still works
