### ISSUE TITLE
[Feature request] Save in a file and redirect to STDOUT

### ISSUE THREAD

**Issue by loustak** [naelstrof/maim#182]
I would like to be able to do something like this: `maim ~/screenshots/screen.png | xclip -selection clipboard -t image/png`. 

Is it possible to add an option to maim to save the picture in a file but also to redirect it's output to STDOUT? (or maybe there is a simple way to do this?)

Thanks.

**Comment by Plasma-Vortex** [comment]
Try this: `maim | tee ~/screenshots/screen.png | xclip -selection clipboard -t image/png`

**Comment by loustak** [comment]
Thanks it works!

**Comment by avalonv** [comment]
Could this be added to the list of examples in the documentation? Users who are not command line savvy might not be aware of `tee`
