### ISSUE TITLE
interactive selection

### ISSUE THREAD

**Issue by whoizit** [naelstrof/maim#186]
is it possible to make interactive selection like this? https://github.com/lupoDharkael/flameshot

**Comment by naelstrof** [comment]
Yeah! Simply chain maim into GIMP, Krita, Pinta, or any other image manipulation program.
A tiny bash script could do it like so:
```sh
!#/bin/bash
maim /tmp/screenshot.png
gimp /tmp/screenshot.png
```
Key is to find a simple image editor that suits what you need or simply configure/modify one of the existing editors. You're only limited by your imagination and programming skills.

A cheap hack for doing quick freeze crops of the screen would look like this:
```sh
!#/bin/bash
maim /tmp/screenshot.png
feh -x -F /tmp/screenshot.png &
id=$!
maim -s /tmp/croppedshot.png
kill $id
```

Replace feh with something that can draw arrows or blur sections of the screen and you got exactly what you're asking for.
