### ISSUE TITLE
Fedora 31 copr builds

### ISSUE THREAD

**Issue by watzon** [naelstrof/maim#195]
Right now if I want to use this in Fedora 31 I have to build from source. It would be nice to have a copr build for Fedora 31 so I could just install from there.

**Comment by watzon** [comment]
Looks like it might be @shymega that's maintaining that?

**Comment by shymega** [comment]
My COPR build is unofficial. I created it when I was using Fedora. I currently use OpenSUSE, but I don't mind keeping my COPR build online until maim is in the Fedora repos..

**Comment by watzon** [comment]
Which hopefully comes soon. Maim is much better than scrot.

**Comment by shymega** [comment]
It is, yes. I've just bumped my COPR repo for maim to v5.5.3, and enabled Fedora 31 builds as well. I hope that helps with your usecase. I don't build from Git, but I'm planning to redo my COPR builds into one repo, to make it easier for me to manage - not sure yet, though.

 If Git builds are wanted, I _suppose_ I could offer them, but I don't see the need... tagged releases are at least somewhat more stable than Git builds.

**Comment by shymega** [comment]
Oh, also, #185 seems to indicate its officially packaged now. Could you try that package, see if it works for you? Would save me having to keep `maim-copr` online.

**Comment by watzon** [comment]
What do you know, there it is. Yay maim!

**Comment by shymega** [comment]
Right, so I'll stop maintaining maim-copr now then, and shut it down. No need for it now, and I think it would just add to more confusion. Thoughts?

**Comment by watzon** [comment]
If it's in the official repository now I'd tend to agree
