### ISSUE TITLE
Delay selection screenshot

### ISSUE THREAD

**Issue by imaojun** [naelstrof/maim#200]
I'm a bit confused when using delayed screenshots. 

![Peek 2020-02-22 21-05](https://user-images.githubusercontent.com/28778042/75092861-2b2d8100-55b7-11ea-8ea6-3d2c271ca36a.gif)

When you enter the following command: 
```bash
$ maim  -s -d 3 foo.png
```

The screenshot will take effect immediately instead of delaying the screenshot first.
And after the screenshot, the delay started to work.

**What should I do to delay the time before take the screenshot?**
now I write the command in the script, with the sleep command in front.

## info
OS:Archlinu
wm:Bspwm
terninal:termite
maim: v5.5.3

**Comment by foxpy** [comment]
>  now I write the command in the script, with the sleep command in front.
I think this is the intended way to delay screenshot selection tool.
The `-d` option of maim is useful when you want to select region first, but take actual screenshot later.
