### ISSUE TITLE
Error when using convert for color picker command

### ISSUE THREAD

**Issue by minikN** [naelstrof/maim#214]
I'm trying to get this command to work:
```
maim -st 0 | convert - -resize 1x1\! -format '%[pixel:p{0,0}]' info:-
```
However, I'm getting this error:
```
~ $ maim -st 0 | convert - -resize 1x1\! -format '%[pixel:p{0,0}]' info:-
convert: no decode delegate for this image format `' @ error/constitute.c/ReadImage/562.
convert: no images defined `info:-' @ error/convert.c/ConvertImageCommand/3285.
```

I guess I'm missing some libraries for ImageMagick. Which one though? `libpng` is installed.
I'm on Void Linux if that helps.

Thanks.

**Comment by foxpy** [comment]
If you are 100% sure you are missing some libraries (doubt), I suggest you running `ldd "$(which convert)"`. If there are any missing shared libraries, `ldd` is going to point you at them.
