### ISSUE TITLE
Full screenshot only works with filepath argument

### ISSUE THREAD

**Issue by rosshadden** [naelstrof/maim#222]
I can only take a full screenshot if I pass a filepath.

These: work:

- `maim /tmp/foo.png`
- `maim --select | xclip -selection clipboard -target image/png`
- `maim --select --tolerance=9999999 | xclip -selection clipboard -target image/png`
- `maim --window=$(xdotool getactivewindow) | xclip -selection clipboard -target image/png`

These do not work:

- `maim | xclip -selection clipboard -target image/png`
- `maim /dev/stdout | xclip -selection clipboard -target image/png`

The working commands show that it's neither the "copy to clipboard" part nor taking a screenshot of my full desktop causing problems on their own. But using them together does not work for me.

This is the X error I get, though likely unhelpful:

```
X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  18 (X_ChangeProperty)
  Resource id in failed request:  0x1600037
  Serial number of failed request:  19
  Current serial number in output stream:  19
```

**Comment by foxpy** [comment]
Please try running

```bash
maim | file -
maim /dev/stdout | file -
```

These should work just fine with `file` indicating valid PNG image (and that means `maim` is working well).

Talking about X error you get, `xclip` always has been kinda unreliable application for me.

**Comment by naelstrof** [comment]
I tested all of these commands and they all appear to be working on the newest maim (v5.7.4) on x11. Maim doesn't work on wayland. Reopen if you still have trouble.
