### ISSUE TITLE
Repeat last capture

### ISSUE THREAD

**Issue by pglira** [naelstrof/maim#228]
Is there any way to repeat the last capture using the previously selected area?

**Comment by foxpy** [comment]
You can remember previously selected area by calling [slop](https://github.com/naelstrof/slop) manually.

**Comment by pglira** [comment]
Works great, thank you!

Save region:
```
#!/bin/bash
geometry=$(slop -b 3)
echo ${geometry} > /tmp/geometry.txt
maim -g ${geometry}
```

Load region to repeat capture:
```
#!/bin/bash
geometry=$(</tmp/geometry.txt)
maim -g ${geometry}
```
