### ISSUE TITLE
Mouse cursor visible with -s in urxvt

### ISSUE THREAD

**Issue by leaty** [naelstrof/maim#229]
![screen 2021-04-04 22 38 59](https://user-images.githubusercontent.com/4429327/113520942-93121180-9596-11eb-8146-d19c9917ed5c.png)

I have a large custom cursor, when using `-s` and drag-selecting on top of urxvt, I get a piece of the cursor left in the image. It seems to work fine in other applications such as firefox, though I've not tested other terminals. Compositor on/off doesn't matter, the above image is taken when `picom` is off.

You could blame my giant cursor like she said, but this doesn't happen with `scrot`. One solution is to drag the cursor insanely quick as soon as you let go, but it's really difficult to pull off.

At least the left/top borders are gone when using maim/slop :+1:

**Comment by leaty** [comment]
After some testing I managed to make it fail in firefox as well, by drag-selecting onto some text. So now I know why it happens, it happens when the mouse changes into a "text cursor" after you're done selecting, which in my case is large enough to imprint the selected area. Any ideas? Is it even _possible_ to fix? Or should I just... _shrink_.

**Comment by foxpy** [comment]
There is a flag in maim:
```
-u, --hidecursor
              By  default  maim super-imposes the cursor onto the image, you can
              disable that behavior with this flag.
```
Have you tried this one?

**Comment by leaty** [comment]
Oof!

I can't believe how simple that was, I wish I'd checked but at the same time I don't think I would've guessed such an option would exist. Thanks a lot!

**Comment by foxpy** [comment]
> I don't think I would've guessed such an option would exist.

Ye, that sometimes happens with me, too.



> Thanks a lot!

You are welcome.
