### ISSUE TITLE
An example command does not work

### ISSUE THREAD

**Issue by dakyskye** [naelstrof/maim#230]
One of the commands from [examples](https://github.com/naelstrof/maim#examples) do not work. To be precise, I am talking about `maim -st 9999999 | convert - \( +clone -background black -shadow 80x3+5+5 \) +swap -background none -layers merge +repage shadow.png`

```
$ maim -st 9999999 | convert - \( +clone -background black -shadow 80x3+5+5 \) +swap -background none -layers merge +repage shadow.png
convert: invalid image index `/tmp/magick-NO1x7WKHVn_TJH7R6UhQO_wW5UVRhpL1' @ error/list.c/CloneImages/282.
convert: no such image `+clone' @ error/convert.c/ConvertImageCommand/1027.
```

**Comment by foxpy** [comment]
works on my machine ™

**Comment by foxpy** [comment]
It may depend on your shell, distribution and many other things.
What is your shell and distribution?

**Comment by dakyskye** [comment]
@foxpy Gentoo, bash 5.0.18.

**Comment by dakyskye** [comment]
```
$ slop --version
v7.5

$ maim --version
v5.6.3

$ convert --version
Version: ImageMagick 7.0.11-7 Q16 x86_64 2021-04-12 https://imagemagick.org
Copyright: (C) 1999-2021 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC Modules OpenMP(4.5) 
Delegates (built-in): bzlib cairo freetype jng jpeg lcms ltdl pangocairo png rsvg tiff x xml zlib
```

**Comment by foxpy** [comment]
My imagemagick package reports more delegates:

```
Delegates (built-in): bzlib cairo djvu fontconfig freetype heic jbig jng jp2 jpeg lcms lqr ltdl lzma openexr pangocairo png raqm raw rsvg tiff webp wmf x xml zip zlib
```

Considering your distribution being gentoo, you may have probably built imagemagick without some features used in previously mentioned one-liner.

**Comment by dakyskye** [comment]
All right, it makes sense. Those purple ones are not included in my ImageMagick build.
![image](https://user-images.githubusercontent.com/32128756/117065420-8b31c280-ad38-11eb-9a7f-a86439103def.png)

**Comment by dakyskye** [comment]
Which one do you think I need for that?

**Comment by foxpy** [comment]
> Which one do you think I need for that?

For a good start, I would just try including every feature possible to check if it fixes the problem. If problem remains unfixed, it is somewhere else...

**Comment by dakyskye** [comment]
All right, I will try and report the result here.

**Comment by foxpy** [comment]
To be honest I don't see any relation between these features and your error message, but we should probably try building imagemagick with all the features anyway.

**Comment by dakyskye** [comment]
Built with Every USE flag except two. Still the same result.
![image](https://user-images.githubusercontent.com/32128756/117130599-57df4a00-adb1-11eb-9d20-35c09b5b8fd8.png)

**Comment by foxpy** [comment]
Try downloading this [image](https://share.rfnull.com/maim-issue-1/test.png) and running `convert - \( +clone -background black -shadow 80x3+5+5 \) +swap -background none -layers merge +repage shadow.png < test.png`

**Comment by dakyskye** [comment]
@foxpy 
![image](https://user-images.githubusercontent.com/32128756/117132995-b78b2480-adb4-11eb-8caa-7190ae20904d.png)

**Comment by dakyskye** [comment]
So it's an issue with ImageMagick itself, but I've built it with all USE flags.. hmm, weird.

**Comment by foxpy** [comment]
> So it's an issue with ImageMagick itself, but I've built it with all USE flags.. hmm, weird.

Yep! Considering you are on gentoo I can assume you have been using Arch in past and you may be familiar with Arch build system.

This is how they build imagemagick: https://github.com/archlinux/svntogit-packages/blob/packages/imagemagick/trunk/PKGBUILD

Maybe gentoo's USE flags don't cover some of the features enabled here? I have no idea.

**Comment by dakyskye** [comment]
Yeah I've been using Arch in the past. I'll have a look at this in a couple of hours when I get home. Thanks for your kind support.

**Comment by foxpy** [comment]
@dakyskye is this issue still relevant?

**Comment by dakyskye** [comment]
@foxpy this issue should be closed as the reported thing isn't related to maim itself, but ImageMagick. (tho, I still can't get it working :man_shrugging:)

**Comment by foxpy** [comment]
> I still can't get it working

Amazing! Computers barely Work™

> this issue should be closed

I don't have any rights in this repository so it would be very kind of You to close this issue by yourself.
