### ISSUE TITLE
what():  Couldn't grab the mouse after 10 tries.

### ISSUE THREAD

**Issue by nsajko** [naelstrof/maim#231]
I have the Archlinux package maim 5.6.3 with Xorg 1.20.11 and Qt5 5.15.2.

I start maim like this: `maim -u -m 10 -s -o p.png`

Usually taking screenshots works just fine, but there's this one Qt 5 program called [Graphia](https://github.com/graphia-app/graphia), where if I open a drop-down menu and try to take a screenshot, maim fails with this output:

```
terminate called after throwing an instance of 'std::runtime_error'
  what():  Couldn't grab the mouse after 10 tries.
```

It also says "Aborted" and dumps core.

**Comment by naelstrof** [comment]
Yeah, this is an Xorg issue, if maim can't grab the mouse, then mouse events would fall through. (Causing clicks to actually affect the desktop.)

There's no mouse grab queue, so other apps can easily get exclusive control. This also works in reverse (maim can prevent QT or i3 menus from functioning properly as well.)

It's a big pain but something that we just have to live with-- unless X decides to rework the mouse grab system.
