### ISSUE TITLE
Screenshotting a monitor instead of the entire screen

### ISSUE THREAD

**Issue by Alee14** [naelstrof/maim#235]
Hello, 
I would like to know if there's a way I can take a screenshot on one monitor instead of it taking two monitors.

**Comment by foxpy** [comment]
> Hello,
> I would like to know if there's a way I can take a screenshot on one monitor instead of it taking two monitors.

Currently I don't have any external monitors I could connect to my laptop to debug this, but there are some useful hints for you:

1) use `xrandr`. It outputs size of screen which you could use later as argument for maim. For example:

```
Screen 0: minimum 8 x 8, current 1366 x 768, maximum 32767 x 32767
LVDS1 connected primary 1366x768+0+0 (normal left inverted right x axis y axis) 280mm x 160mm
```

We are interested in parameter `1366x768+0+0`.

2) use maim flag `-g` and pass parameter from hint 1 into it, this will make maim capture only specified screen.

**Comment by Alee14** [comment]
Ahh thanks
