### ISSUE TITLE
Apps freeze when copying

### ISSUE THREAD

**Issue by santilococo** [naelstrof/maim#236]
Hi, if I take a screenshot of my dwm desktop (only the root window without any programs) and then try to copy the screenshot to another application, it will freeze until I copy something else. Do you know what could be happening? TY. I have dwm + picom (but without picom it's the same).

**Comment by foxpy** [comment]
> it will freeze until I copy something else

I don't get what exactly gets freezed, could you please elaborate on this?

**Comment by santilococo** [comment]
Hi! The app I am trying to paste into will freeze. For example, If I take a screenshot (`maim -k -s | xclip-clipboard selection -t image/png`) and then try to copy its output to Discord, Discord will freeze. Hope I was clearer... TY.

**Comment by foxpy** [comment]
> Hi! The app I am trying to paste into will freeze. For example, If I take a screenshot (`maim -k -s | xclip-clipboard selection -t image/png`) and then try to copy its output to Discord, Discord will freeze. Hope I was clearer... TY.

The part with `xclip-clipboard` looks odd for me. Can you try running `maim -k -s | xclip -selection clipboard -t image/png`?
To be honest, I am not sure if it would fix anything for you, it just a first odd thing which looks unnatural for me.

Also, this is not the first clipboard related issue, e.g. try looking at: #211 #180 

All these issues are not really related to maim. I advise you to check out if maim works properly like this:

```
$ maim -k -s | file -
/dev/stdin: PNG image data, 180 x 128, 8-bit/color RGBA, non-interlaced
```

As you can see, in my case maim generates valid PNG image which can be further piped into other applications
or clipboard managers. Any clipboard issues can't be fixed on maim side.

**Comment by JimPix1** [comment]
Hi @santilococo
Did you find the solution to this bug? I believe I have the same identical problem :)

**Comment by foxpy** [comment]
> I have the same identical problem

Everyone has. This issue is not about maim, but either about xclip, X11 or freezing applications theirselves. To be honest I don't even have an idea of where to start debugging.

**Comment by foxpy** [comment]
Actually go check out #260, it may help you
