### ISSUE TITLE
Completion of dependency specification in a build script

### ISSUE THREAD

**Issue by elfring** [naelstrof/maim#24]
I suggest to correct [the handling around the programs "gengetopt" and "cp"](https://github.com/naelstrof/maim/blob/6888fa94a9a342993562e1158093d58a402d880b/CMakeLists.txt#L33) by the reuse of [the CMake functionality "add_custom_command"](http://www.cmake.org/cmake/help/v3.0/command/add_custom_command.html).

**Comment by naelstrof** [comment]
Unnecessary now with the new release: https://github.com/naelstrof/maim/releases/tag/v4.4.47
