### ISSUE TITLE
How would I make a command to both save a screenshot and copy it to the clipboard?

### ISSUE THREAD

**Issue by ytfcon** [naelstrof/maim#241]
I've tried "maim -s ~/Pictures/Screenshots/$(date +%s).png | xclip -selection clipboard -t image/png", and it manages to save the image, but the clipboard output is always broken. The clipboard example that is given (maim -i $(xdotool getactivewindow) | xclip -selection clipboard -t image/png) works for me so I don't know where exactly I'm going wrong.

**Comment by foxpy** [comment]
Your problem is that when you call maim with a specified path to save an image, it only gets written to a file, and not to stdout.
xclip expects some image from stdout, but there is nothing.

You should rewrite your command a bit:
```bash
path="$HOME/Pictures/Screenshots/$(date +%s).png" && maim -s "$path" && xclip -selection clipboard -t image/png "$path"
```
