### ISSUE TITLE
How to copy images to clipboard on wayland

### ISSUE THREAD

**Issue by biscuitrescue** [naelstrof/maim#245]
does anyone know how to copy to clipboard on wayland, xclip doesnt work

**Comment by foxpy** [comment]
> how to copy to clipboard on wayland

https://superuser.com/questions/1189467/how-to-copy-text-to-the-clipboard-when-using-wayland

**Comment by foxpy** [comment]
I am closing this issue because maim has nothing to do with Wayland, and issue itself is not even related to maim. Feel free to ask any more questions here if you want to, I am still subscribed to all threads and read all posts.
