### ISSUE TITLE
Screenshot using Selection Mode on a Document includes Cursor

### ISSUE THREAD

**Issue by ZN0N15** [naelstrof/maim#248]
I have this very weird problem where trying to screenshot using selection mode -s on a Document where the Cursor changes to the long typing cursor is included in the screenshot at the bottom left corner where the selection stops. It's really hard to explain through words but here's a recording and example of a screenshot.

![screenshot](https://user-images.githubusercontent.com/57549197/150245694-52a66632-7fbd-4882-a930-cf6f6763b382.gif)

![screenshot2022-01-20-09:14:21](https://user-images.githubusercontent.com/57549197/150245807-f64f7c87-f71a-4973-a8e3-c17f6e101d31.png)

I'm not sure if this is a bug on maim, but I have tried changing to multiple cursor themes and making my cursor size smaller, but that didn't seem to fix the issue. The cursor just still appears on the corner of the screenshot and its driving me nuts, I don't want it there.

If this isn't a bug, is there any way to alleviate this issue? Changing cursors sure didn't work..

**Comment by foxpy** [comment]
I have discribed in #244 how to hide cursor from screenshot.
