### ISSUE TITLE
what is the name/class/instance of the window which selection open

### ISSUE THREAD

**Issue by osafaimal** [naelstrof/maim#252]
hello,
i use picom with transparency and blur on unfocused window and i want to make the window that maim -s open excluded of blur for that i must know a property that i can put in picom.conf. 
thanks for help

**Comment by osafaimal** [comment]
find answer in #188

**Comment by foxpy** [comment]
> i find the answer in #188

Should we move put these instructions on GitHub Wiki?

**Comment by osafaimal** [comment]
i think it can be a good thing
