### ISSUE TITLE
cant upload screenshots on reddit

### ISSUE THREAD

**Issue by arnavgr** [naelstrof/maim#259]
This might sound weird but the screenshots that i take with maim cannot be uploaded on reddit. i take screenshots in png format(default) and is supported by reddit , but when i try to upload it . it doesnt appear in supported files list. If i choose all files and select the screenshot it show an error saying failed to upload. what am i supposed to do in this case?

**Comment by foxpy** [comment]
That's… extremely hard to reproduce. You could possibly upload your images so we can at least look at them and see if there's anything wrong.

**Comment by arnavgr** [comment]
i found a workaround by renaming the photo to a different extension.
