### ISSUE TITLE
Image corruption

### ISSUE THREAD

**Issue by 0Karakurt0** [naelstrof/maim#265]
"Streamed" trough pipe image gets corrupted along the way

```
feh WARNING: 2022-10-18_02:09:38.png - Does not look like an image (magic bytes missing)
feh: No loadable images specified.
See 'feh --help' or 'man feh' for detailed usage information
```

Example code
```
 { cat ~/pipe.tmp |\
   tee ~/Images/Screenshots/$(date +%F_%T).png |\
   xclip -selection clipboard -t image/png
 } &
 maim -s -k - > ~/pipe.tmp  
```
switching to **scrot -s - > ~/pipe.tmp** helps, therefore it's maim's bug.

**Comment by foxpy** [comment]
I currently don't have a machine with X11 setup so I cannot test this.

But that's really weird, maim doesn't have different code for saving into file or piping. Could you try piping into `file -` and reading what it says? Should be something like `"PNG image RGBwhatever XxY pixels"`. Otherwise that's really a bug in maim.

**Comment by 0Karakurt0** [comment]
~ ➜ cat pipe.tmp | file -
/dev/stdin: empty
~ ➜

**Comment by foxpy** [comment]
> /dev/stdin: empty

There is just no data! Are you sure that `maim -s -k - > ~/pipe.tmp` actually writes any output?

**Comment by foxpy** [comment]
I suspect maim doesn't support `-` syntax to write to stdout and instead creates file called `-` and writes PNG data into it?
Can you try doing just `maim -s -k > ~/pipe.tmp`?

**Comment by 0Karakurt0** [comment]
That's it!
And I was wondering who the hell spams ~/- me.

Well, I think this should be adjusted to be in line with other unix utilities

**Comment by foxpy** [comment]
> Well, I think this should be adjusted to be in line with other unix utilities

I definitely agree with you.
