### ISSUE TITLE
Parser of maim for image names work incorrectly

### ISSUE THREAD

**Issue by snoitallicso** [naelstrof/maim#268]
~ `date +"%Y-%m-%d %H:%M:%S"`

`2022-11-02 06:23:49`

~ `maim Pictures/$(date +"%Y-%m-%d %H:%M:%S").png`

**`2022-11-02`** file

**Comment by snoitallicso** [comment]
I need to use _ between date and time like:

`maim Pictures/$(date +"%Y-%m-%d %H:%M:%S").png`

**Comment by naelstrof** [comment]
Maim actually has the bare minimum of parsing to read args, it uses [cxxopts](https://github.com/naelstrof/maim/blob/master/src/cxxopts.hpp) to parse. What shell are you using?

I'd recommend trying `maim "Pictures/Screenshots/Maim_Screenshot_$(date +"%Y-%m-%d_%H:%M:%S").png"` to make sure your shell isn't changing the arg.

**Comment by foxpy** [comment]
Closing as not related to maim.
