### ISSUE TITLE
New Fedora package maintainer

### ISSUE THREAD

**Issue by AloisMahdal** [naelstrof/maim#269]
This is not a maim issue; I'm opening this mainly for transparency.

Current status of maim Fedora package:
 *  @AymenQ, who has been maintaining it for some time, has gone quiet,
 *  the Fedora package `maim` [has been already marked as orphaned][bzor],
 *  [latest version present][ver] in Fedora Rawhide is v5.6.3

  [bzor]: https://bugzilla.redhat.com/show_bug.cgi?id=1823039&Bugzilla_restrictlogin=on
  [ver]: https://src.fedoraproject.org/rpms/maim

Because I've been already [maintaining naelstrof/slop][slopm] for some time, I've decided to try and take care of the maim maintenance as well.

  [slopm]: https://github.com/naelstrof/slop/issues/102

This issue is to announce my plan and track my progress with my first update of the maim package (to v5.7.4).  If I succeed, I will start keeping eye on the maim package and updating it in time.

As far as I know, there won't be need for changes in maim just to facilitate the transfer.

**Comment by AloisMahdal** [comment]
OK, passed the build (after adding webp dependency); update has been created: https://bodhi.fedoraproject.org/updates/FEDORA-2022-8bd9ded001

It should now be just a question of time before it bubbles up to rawhide (devel version of fedora).

I will keep an eye on the update and once it's in rawhide, I will try to test it in a VM and report back.

Once I confirm that the update has landed and is maim is working (that should be within few days up to week or so), this issue can be closed.

**Comment by foxpy** [comment]
> Note that maim produced empty PNG (correct size but all pixels transparent) when ran under Gnome Shell + Wayland, which is default for Fedora.

@AloisMahdal please don't waste your precious time on it, maim is a screenshot tool for X11, it doesn't support Wayland.
