### ISSUE TITLE
No screenshots when invoked via custom keyboard shortcut on Gnome

### ISSUE THREAD

**Issue by alvv-z** [naelstrof/maim#271]
I have set up custom shortcuts for `Print` and `Ctrl+Print`, and after working once, neither takes a screenshot now. It seems like maim exits right after calling, without taking a screenshot. I have tried multiple different invocations, including:

- `maim --format='png' --hidecursor --quality 10 --select | xclip -selection clipboard -t image/png` for `Print`
- `maim | tee ~/Pictures/Screenshots/$(date +%s).png | xclip -selection clipboard` for `Ctrl+Print`

with and without the `--nokeyboard` option. When executing the commands from a terminal in any directory, they work.

**Comment by foxpy** [comment]
Try `sh -c 'maim --format="png" --hidecursor --quality 10 --select | xclip -selection clipboard -t image/png'`

**Comment by alvv-z** [comment]
> Try `sh -c 'maim --format="png" --hidecursor --quality 10 --select | xclip -selection clipboard -t image/png'`

You're my savior. Thanks a lot. Do you have any ideas as to why the command has to be wrapped like this? It seems odd since it worked once.

**Comment by alvv-z** [comment]
@foxpy should I close this issue since it is a DE issue, or do you think it's a maim issue?

**Comment by foxpy** [comment]
> @foxpy should I close this issue since it is a DE issue, or do you think it's a maim issue?

I don't think it is an issue at all. I guess previously DE has been passing user-provided snippet to a shell, but now it invokes it as a whole command (hence now you need to pass it in sh).

So, it is not a problem with your DE or with maim.
