### ISSUE TITLE
How to copy screenshot to selection and also download the screenshot in one command?

### ISSUE THREAD

**Issue by levdopa** [naelstrof/maim#275]
I tried
maim -s $(date +%Y-%b-%d--%H-%M-%S).png | xclip -selection clipboatd -t image/png

Also just realized that if I put this as a keybind in my tiling window managers autostart, the date does not update. I will think of a fix later.

**Comment by foxpy** [comment]
> Also just realized that if I put this as a keybind in my tiling window managers autostart, the date does not update.

Maybe there is just some weird caching going on. I suggest you creating a standalone script and calling just it from your window manager, should work fine this way.

> How to copy screenshot to selection and also download the screenshot in one command?

download? huh? please clarify what do you mean under "download".

**Comment by levdopa** [comment]
> download? huh? please clarify what do you mean under "download".

I meant that the screenshot is saved to my home directory as a .png after I take the screenshot. I got it to work in scrot so I'll close the issue.
