### ISSUE TITLE
Adjust the selection area before taking a screenshot

### ISSUE THREAD

**Issue by volodymyrprokopyuk** [naelstrof/maim#281]
Hi,

The current behavior of `maim` takes a snapshot as soon as the mouse left button is released. So the user has only one opportunity to correctly select the area for a screenshot.

Is it possible to adjust the selection area after the mouse left button is released, but before the screenshot is taken. It is very convenient to draw first an approximated selection area, then adjust it from the top/bottom/left/right and only then take a snapshot.

Thank you for a very useful tool!

**Comment by N-R-K** [comment]
> So the user has only one opportunity to correctly select the area for a screenshot.

The initial selection area can be adjusted, see this comment: https://github.com/naelstrof/maim/issues/282#issuecomment-1605533236

**Comment by volodymyrprokopyuk** [comment]
Pressing the `Space` key while holding the mouse left button during the selection to move the selection is quite handy! Thank you!
