### ISSUE TITLE
maim+slop+`--windowid` not working (OSX)

### ISSUE THREAD

**Issue by rafi** [naelstrof/maim#38]
The only way maim works for me on OSX is by specifying `--windowid`, otherwise I'm getting empty black images, with just the cursor visible. However combining with slop, `-s`, I always get black shots with just the cursor visible.

``` sh
$ maim -i $(xdotool getactivewindow) test_maim.png  # Works!

$ maim -s -i $(xdotool getactivewindow) test_slop.png  # Black image with cursor only
$ maim -s --localize -i $(xdotool getactivewindow) test_slop.png  # Black image with cursor only
```

**Comment by naelstrof** [comment]
Heh sorry, I don't have a Mac to test maim on. I'm not quite sure what the issue is, I'm going to get a virtual machine real quick to test it.

Thanks for reporting this!

**Comment by rafi** [comment]
Thanks, I would happily test any fix branches and help out.

**Comment by naelstrof** [comment]
Sorry for such slow developments, I actually still haven't been able to get a working virtual machine of OSX.
OSX is designed to not work in virtual machines on purpose, and I still have no way of testing or fixing this issue still.

I'll keep trying to get a working virtual machine, but otherwise this issue is at a stand-still.

**Comment by rafi** [comment]
Thanks for the update!

**Comment by naelstrof** [comment]
Ok I got a working virtual osx, I promptly installed homebrew, XQuartz, and imlib2. I built slop and maim, and found they don't work at all on normal windows.

Windows created by XQuartz seem to get screenshotted fine, in fact the mouse can't even be grabbed by slop unless I hover over a XQuartz window.

In XQuartz's preferences can you turn on the fullscreen mode? Then take a screenshot with `maim --mask=off`?
The root window must be enabled for maim to function, and Xrandr wasn't working properly on my virtual machine. Maybe it will help you? (Enabling fullscreen for me just turned the screen black haha.)

I can't debug much further as the virtual machine makes it really hard to tell what is maim's fault, what's XQuartz's fault, and what's the virtual machine's fault.

If you have a chat client like Steam or Mumble I wouldn't mind working on this problem with you, as it seems I'm unable to get a good Mac setup going without an actual mac.

**Comment by rafi** [comment]
Same behavior in full-screen mode. `maim` will only produce non-blank images with `-i $(xdotool getactivewindow)`, doesn't matter if `--mask` is off/on, but as soon as combined with `-s` - images are blank... :(

**Comment by naelstrof** [comment]
Behavior may be improved with the new release: https://github.com/naelstrof/maim/releases/tag/v4.4.47

You may want to give it another shot.

**Comment by naelstrof** [comment]
Mac OS isn't supported by me anyway. I can't afford a mac-book, and when I tried using a virtual machine the OpenGL didn't work very well.

Feel free to reopen if you have more info though.
