### ISSUE TITLE
Using maim to take full screenshots produces blank pictures in tiling window managers

### ISSUE THREAD

**Issue by Meistache** [naelstrof/maim#39]
Hello. I've done the test in my three desktop environments at Linux Mint 17.1
imlib2 version is 1.4.6-2 from repository

I'm using most tiling WMs since my Cinnamon started to act weird (only in 3D acceleration though, so I could test it using software rendering). Mostly BSPWM but I have StumpWM as well so I tested it into both. I've noted that my screenshots (I usually use Poomf script for uploading them in a puu.sh-style) were being uploaded as blanks. So I started testing what was up.

Running maim --hidecursor <file> or maim <file> produced blanks. However using coordinates (-h -w -x -y) or using slop mode with -s just worked fine. To complete this I've tried taking a shot with ImageMagick (import -window root <file>) and it just worked fine. Then I re-installed imlib2 and tried all again. So I went from BSPWM from Cinnamon and tried maim --hidecursor and maim and well, it worked too. So I decided to try StumpWM and... curiously I've got the same problem as BSPWM.

So I think it's something specially ocurring with tiling WMs (maybe because they use a tree approach to rooting windows and tiling them instead of a root workspace with grips and floating windows with no parental relationship. Dunno, only my guess). Please let me know if I can contribute with any additional information.

**Comment by naelstrof** [comment]
Do you have a multi-monitor set-up? Can you try running `maim --mask="off"` to see if that makes a difference?

Does scrot have the same problems?

**Comment by Meistache** [comment]
Nope, only a CRT head, 1280x1024. And yes, it does work with maim --mask="off", never tried it before. 

Actually never used scrot before. Worth testing in this case?

**Comment by naelstrof** [comment]
i see. Not worth testing scrot as masking is the problem. For now just disable masking. The window manager seems to be misreporting the screen/window sizes.

**Comment by naelstrof** [comment]
I got BSPWM and I couldn't replicate the issue, maim worked fine in i3 too. I don't believe that the window manager is the problem.

Your Xrandr X11 extension is reporting that it is working, but is giving wrong information.
You may want to make sure xrandr is installed and working properly, can you tell me the output of ```xrandr``` in a terminal please?

**Comment by tb01110100** [comment]
Can confirm this issue. Am using bspwm and have 2 monitors. [Here's](https://ptpb.pw/hmiE) the output of `xrand` on my machine.

**Comment by naelstrof** [comment]
Can you post your bspwm configuration? XRandR seems to be working fine on your system, does it work fine without masking?

**Comment by Airblader** [comment]
I have the same issue, but it only occurs from time to time. Working with `-s` works fine. Anything I can do to help figuring this out?

**Comment by naelstrof** [comment]
Could you try the new release and tell me if there's an issue?
https://github.com/naelstrof/maim/releases/tag/v4.4.47

**Comment by Airblader** [comment]
I haven't experienced this issue in a while, so I assume it's fixed.

**Comment by naelstrof** [comment]
Thanks for the feedback
