### ISSUE TITLE
Dimmed selection screenshots

### ISSUE THREAD

**Issue by bigmittens** [naelstrof/maim#40]
https://i.imgur.com/h26F6sY.png (since github doesn't want to upload it)

Whenever I take a selection screenshot now the dim for the selection just stays.

**Comment by bigmittens** [comment]
https://en.wikipedia.org/wiki/Malapropism

**Comment by naelstrof** [comment]
Is this related do you think? https://github.com/naelstrof/slop/issues/18

Your compositor is probably putting a shadow on slop's window, and as it closes maim takes a screenshot, erroneously screenshotting the shadow.

Slop's windows are flagged to not be under the effects of the window manager, but sometimes compositors ignore the CWOverrideRedirect flag anyway. You'll have to add windows with the class/name of "slop" to the exception list of your compositor.

**Comment by bigmittens** [comment]
Yup, that did the trick. Thanks.

**Comment by Brottweiler** [comment]
@bigmittens Could you share how you fixed this? I assume you use compton, as I.
