### ISSUE TITLE
select error

### ISSUE THREAD

**Issue by r8b7xy** [naelstrof/maim#41]
When I try to run `maim -s` and mouse is over any window and I select it maim gives an error:
```
X Error of failed request:  BadMatch (invalid parameter attributes)
  Major opcode of failed request:  73 (X_GetImage)
  Serial number of failed request:  25  
  Current serial number in output stream:  25  
```
Problem doesn't appear when mouse is over lemonbar and then I select the window I'd like to print (bspwm@arch).
[video](https://youtu.be/FJWQyNgK4Jo)

**Comment by naelstrof** [comment]
Does running `slop` have the same issue?

**Comment by naelstrof** [comment]
What kind of effect does using the `--nodecorations` or `-n` flag have in maim or slop?

**Comment by r8b7xy** [comment]
$ slop
```
X=641
Y=520
W=3
H=1
G=3x1+641+520
ID=152
Cancel=false
```
$ slop -n
```
_X Error of failed request: BadWindow (invalid Window parameter)
_  Error code of failed request:   3
_  Major opcode of failed request:  38
_  Minor opcode of failed request:   0
_  Serial number of failed request:    69
_  Current serial number in output stream:?????
```
$ maim -ns
```
X Error of failed request:  BadMatch (invalid parameter attributes)
  Major opcode of failed request:  73 (X_GetImage)
  Serial number of failed request:  25
  Current serial number in output stream:  25
```

**Comment by naelstrof** [comment]
Seems like I'll have to boot up bspwm and test it myself. Last time I tried it ran flawlessly.

I'll have more questions after I fiddle around.

**Comment by r8b7xy** [comment]
It was bspwm bug which was fixed in latest commit https://github.com/baskerville/bspwm/commit/56895ab9ab074877d5af92aa1367699d1b351a38
