### ISSUE TITLE
Cant install maim on Linux Mint

### ISSUE THREAD

**Issue by SebastiaanHolthuis** [naelstrof/maim#46]
Hello,

Earlier today I tried to install maim on Linux Mint. I got this error and it didn't install:
[ 25%] Building CXX object CMakeFiles/maim.dir/src/im.cpp.o
/home/sebastiaan/maim/src/im.cpp: In member function ‘int maim::IMEngine::blendCursor(Window, int, int)’:
/home/sebastiaan/maim/src/im.cpp:135:39: error: variable-sized object ‘pixels’ may not be initialized
     DATA32 pixels [ size_px ] = { 0x0 };
                                       ^
make[2]: *** [CMakeFiles/maim.dir/src/im.cpp.o] Error 1
make[1]: *** [CMakeFiles/maim.dir/all] Error 2
make: *** [all] Error 2

I've installed all the requires tools and programs.

**Comment by naelstrof** [comment]
Should be fixed with 9d9ef146d6007a269dc2a9a4b11ea26ed4837669, sorry for the inconvenience!

**Comment by naelstrof** [comment]
This issue will remain open until it's confirmed fixed. Sebastiaan, it would be nice if you could respond.

**Comment by SebastiaanHolthuis** [comment]
Fixed now. Thanks.
