### ISSUE TITLE
Inconsistency detected by ld.so

### ISSUE THREAD

**Issue by inn0kenty** [naelstrof/maim#50]
I run maim on Arch Linux and got this error:
"Inconsistency detected by ld.so: dl-version.c: 224: _dl_check_map_versions: Assertion `needed != ((void *)0)' failed!"

**Comment by naelstrof** [comment]
One of your libraries is missing or the wrong version.

Try compiling maim-git from the AUR and tell me how that works.

**Comment by inn0kenty** [comment]
maim-git works correctly
Thanks!
