### ISSUE TITLE
maim with slop leaves grey overlay on screenshots

### ISSUE THREAD

**Issue by 0x72** [naelstrof/maim#54]
I use sxhkd to bind ctrl + Print to 'maim -s ~/screenshots/$(date +%F-%T).png'.
This works, but the resulting screenshots have a dark tint, apparently because maim takes a screenshot while the grey overlay of slop is still visible.
This does not happen when I use maim without slop to capture a fullscreen screenshot.
Example screenshot:
![2015-09-23-23 25 45](https://cloud.githubusercontent.com/assets/12549786/10059430/336269b2-624b-11e5-90cc-77da342d0621.png)

**Comment by naelstrof** [comment]
What composition manager are you using? Looks like a shadow is being left behind after slop's window is destroyed.
You should add an exception to your composition manager that excludes windows with a class or name of *slop* from getting shadows or other kinds of processing.

You might want to look at the other similar issues: #40, [#18](https://github.com/naelstrof/slop/issues/18)

**Comment by 0x72** [comment]
Thanks, your reponse time is insane. That was the solution and I admit it was a stupid question, I could have searched previous Issues. Still learning Github. I thought the grey overlay that appeared for slop was intended, but instead it was just compton drawing a fullscreen shadow. For future reference, start compton with compton -bcCGf --shadow-exclude 'class_g = "slop"'

**Comment by naelstrof** [comment]
No question is stupid. Glad you brought it up so maybe the next person to have the problem can find the solution more easily.

I'm going to if the compton team could add *slop* to a default exclusion list or something. Thanks for posting your solution as well.

**Comment by EvanPurkhiser** [comment]
I'm having a similar problem (seemingly randomly, it only happens *sometimes*) using: `maim -slc '0,0,0,0.15'`.

I'm using compton *without* shadows enabled, I've even tried using the shadow-exclude option as follows:

```ini
backend              = "xr_glx_hybrid"
vsync                = "opengl-swc"
glx-no-rebind-pixmap = true
glx-no-stencil       = true
paint-on-overlay     = true
unredir-if-possible  = true
shadow-exclude       = ["name = 'Screenshot'", "class_g = 'slop'"]
```

**Comment by naelstrof** [comment]
Have you tried using the --opengl option?

**Comment by EvanPurkhiser** [comment]
I'll give that a try and report back. Thanks @naelstrof. I presume there may be a reason I configured it with `opengl-swc`.

**Comment by EvanPurkhiser** [comment]
Still getting this problem with the `opengl` option (instead of `opengl-swc`). I assume there's some kind of painting timing bug. I'll try playing around with more options.
