### ISSUE TITLE
jpeg quality choice

### ISSUE THREAD

**Issue by Sergey82** [naelstrof/maim#55]
can not find how to set quality of output image in jpg format output file

**Comment by naelstrof** [comment]
Currently there is no way to set the jpg quality in maim, and digging through imlib2's source code reveals that jpg save at a 75 quality by default.

To set the quality myself I have to use a function not described in the Imlib2 documentation:
```C++
void                __imlib_AttachTag(ImlibImage * im, const char *key,
                                      int val, void *data,
                                      ImlibDataDestructorFunction destructor);
```
I'll do some testing to get it to work, but a work-around you can use now is just save a png and convert it to a jpg using ImageMagick/Gimp/etc using the settings you desire.
Sorry for the inconvenience, and thanks!

**Comment by Sergey82** [comment]
thanks for the concerning. i choosed jpg because of the speed and that i
was unable to use pnm formated image from maim in convert utility, convert
did said that there was something wrong with the image if it was in pnm or
bmp formats. similiar problem was when i tried to open an image in gimp or
pinta. command used was looking like: maim -g 100x100+100+100 image.pnm.
jpeg worked fine with an exeption of default image quality setting ~ 75%

2016-01-01 3:09 GMT+06:00 Dalton Nell <notifications@github.com>:

**Comment by naelstrof** [comment]
It should be `maim -g 100x100+100+100 image.png` I don't believe pnm is a format.

**Comment by Sergey82** [comment]
yes pnm is a format. much like bmp, pnm is a bit map. and no the command i
typed was a command i wish to use, it was not a mistype. png is too slow,
0.5 sec to save. the delay is unsatifying. comparing to jpeg's 0.05 sec.
ten times less is fine ratio by me.
well no problem, the tool is free in any way. thanx for chatting.

2016-01-08 15:10 GMT+06:00 Dalton Nell <notifications@github.com>:

**Comment by naelstrof** [comment]
Done: https://github.com/naelstrof/maim/commit/626b9dd0df3dba1038f7f0452e1a7942e57a0e36
