### ISSUE TITLE
Command sed not found.

### ISSUE THREAD

**Issue by kusayuzayushko** [naelstrof/maim#59]
```
Warning: Command gengetopt or sed not found! Won't regenerate command line code. 
...
$which sed
/bin/sed
```
i'm using Ubuntu based Linux MInt.

**Comment by naelstrof** [comment]
It's just a warning, the command line code is already included pre-generated. If it's not compiling I'll need more output than that.

**Comment by kusayuzayushko** [comment]
I posted in just in case. It seemed strange that it did not find sed, but nvm.
