### ISSUE TITLE
how can i change the maim default folder

### ISSUE THREAD

**Issue by dplord** [naelstrof/maim#64]
everytime when i take a screenshot, it will create image file at ~/your-png-file
but i want it create image file at ~/my-specified-folder/your-png-file by default

is there anyway to do it??

**Comment by naelstrof** [comment]
This is a feature left up to the terminal.
Putting 
`alias maim="maim ~/blah/$(date +%s).png"`
in your bashrc would set the default folder to ~/blah.

**Comment by delborges** [comment]
Putting `alias maim="maim ~/blah/$(date +%s).png"` on our bashrc will work only when the command is launched from terminal, right? I've tried to keybind a command, but's not saving to the path configured on my bashrc, only works when launched from the terminal.

I've tried to put the entire command to a keybing too, and, again, can't get this working.
`maim ~/Imagens/Screenshots/screenshot_$(date +%F-%T).png`
![screenshot_2016-10-15-15 17 22](https://cloud.githubusercontent.com/assets/9376169/19412386/772dbe2c-92eb-11e6-8276-8e9c41f4ea99.png)

**Comment by daltomi** [comment]
It is possible that the program you are using does not interpret commands bash.

Try: `bash -c "maim ~/Imagens/Screenshots/screenshot_$(date +%F-%T).png"`

Or: `/usr/bin/bash -c "maim ~/Imagens/Screenshots/screenshot_$(date +%F-%T).png"`

This works with "keyboard shortcuts" in XFCE.
