### ISSUE TITLE
Fastest screenshooter: scrot, maim or something else?

### ISSUE THREAD

**Issue by Symbian9** [naelstrof/maim#66]
http://pastebin.com/Ja2MWHMm

REFERENCES:
- http://www.linux.org.ru/forum/desktop/12928579

**Comment by anarcat** [comment]
pastebin: "This page has been removed!"

the other page is in russian - can you translate?

**Comment by naelstrof** [comment]
If I remember correctly, the pastebin was evidence that maim performed poorly compared to other screen shooters by a couple milliseconds. I believe it's due to maim doing some masking when multiple monitors are involved.

**Comment by anarcat** [comment]
ah. interesting. it'd sure be nice to have an idea of how to reproduce those results...

**Comment by naelstrof** [comment]
Here's a script I made for it.
``` sh
!/bin/sh

echo "import timing"
echo "---"
time for i in {1..10}; do
    import -window root -define png:compression-level=9 test.png;
done
echo "
"

echo "scrot timing"
echo "---"
time for i in {1..10}; do
    scrot --quality 0 test.png;
done
echo "
"

echo "maim timing"
echo "---"
time for i in {1..10}; do
    maim --quality=10 test.png;
done
echo "
"
```

and the result

``` sh
import timing
---

real	0m3.146s
user	0m2.950s
sys	0m0.130s


scrot timing
---

real	0m2.198s
user	0m2.043s
sys	0m0.067s


maim timing
---

real	0m2.468s
user	0m2.283s
sys	0m0.117s

````

Scrot wins, Imlib2 is a pretty optimized library. Though maim does pretty well for using a homebrewed image library.

**Comment by anarcat** [comment]
i get a syntax error with your script, but that's a good indicator... here are my results and updated script:

```bash
[1026]anarcat@curie:~$ cat bench-snaps 
#!/bin/bash

output=test.png

echo "import timing"
echo "---"
time for i in {1..10}; do
    import -window root "$output";
done
echo

echo "scrot timing"
echo "---"
time for i in {1..10}; do
    scrot "$output";
done
echo

echo "maim timing"
echo "---"
time for i in {1..10}; do
    maim "$output";
done
echo

[1025]anarcat@curie:~$ ./bench-snaps 
import timing
---

real	0m2,389s
user	0m2,260s
sys	0m0,088s

scrot timing
---

real	0m1,222s
user	0m1,152s
sys	0m0,016s

maim timing
---

real	0m1,580s
user	0m1,488s
sys	0m0,032s

```

i wonder why maim has its own image lib...

**Comment by naelstrof** [comment]
maim has it's own image lib because of this: https://github.com/naelstrof/maim/issues/71.
imlib2 was bugged and unmaintained causing maim to break.

**Comment by naelstrof** [comment]
Oh and I just noticed you removed all of the quality settings. That's unfair given they all default to different values.

Scrot, when its quality is set to 0, gives the maximum amount of compression to pngs (9).  Maim defaults to the maximum compression, and I didn't check what import does by default.

**Comment by anarcat** [comment]
that is deliberate: i don't really care what compression is used. most people will always use the defaults so that should be what is compared, not some tweaked setting...

**Comment by anarcat** [comment]
notice  how the relative speed was not really changed anyways...
