### ISSUE TITLE
Screenshot with compositor's shadows

### ISSUE THREAD

**Issue by eti0** [naelstrof/maim#68]
Hey,

I've been using maim for a while but I never asked myself if it could take compton's shadows with a selected window.
If it is possible I'd love to have this feature made available.

If you don't what I mean here's an example:
![screenshot from 2017-01-12 22-27-58](https://cloud.githubusercontent.com/assets/14180792/21909008/6c7cd604-d916-11e6-92a8-d116adbe2e51.png)

But now with shadows.
![screenshot from 2017-01-12 22-27-58-shadows](https://cloud.githubusercontent.com/assets/14180792/21909158/ff684804-d916-11e6-8b77-a4ba63405fc2.png)

**Comment by naelstrof** [comment]
That is outside the scope of maim, since you could chain up commands to create the shadows instead.
Imagemagick is perfectly capable of adding a shadow to an image: http://www.imagemagick.org/Usage/blur/#shadow
Using aliases/scripts you could easily add the functionality yourself.

**Comment by eti0** [comment]
No problem, I guess I could do that.
I was just wondering how hard it would be to implement it instead of scripting it up, like gnome-screenshot does for example.

**Comment by naelstrof** [comment]
It's a lot harder than writing two lines of bash, that's for sure.

**Comment by eti0** [comment]
I guess so.
Thanks anyway, I'll just do a little script for this then.

**Comment by naelstrof** [comment]
Oh yeah, it is important to note that I can screenshot windows with their shadows with maim, you just have to specify the correct window ID. Slop will automatically select the "shadow" window provided you don't specify the `--nodecorations` flag.

**Comment by eti0** [comment]
I don't use slop, I used a simple xdotool command to select the window with a simple click.
I'll look into it thought.
