### ISSUE TITLE
Save in current directory should be more permissive

### ISSUE THREAD

**Issue by nheir** [naelstrof/maim#69]
Basically, `cd /tmp; maim -s` fails because /tmp is not own by current user.

You may want to use `access(dirname, R_OK | W_OK)`

**Comment by naelstrof** [comment]
This should be irrelevant with the new release (which no longer saves to the current directory by default).

Could you tell me if the behavior is improved? https://github.com/naelstrof/maim/releases/tag/v4.4.47

**Comment by nheir** [comment]
Indeed, but now there is no error when trying to write at an unauthorized place.
This is better than a false positive anyway :)
