### ISSUE TITLE
Not working in Dota2

### ISSUE THREAD

**Issue by TimHi** [naelstrof/maim#74]
When i launch maim with a hotkey in a dota2 game (in the menu it works fine) nothing happens, slop's selection isnt even popping up.

I'm fairly sure this is caused by Dota already grabbing the pointer so slop cant do it.

**Comment by naelstrof** [comment]
There's nothing that I can do about this, slop simply can't grab the pointer while another application has commandeered it. You'd have to run maim without the -s option.

Another solution would be to run dota 2 with the startup parameters `-windowed -noborder`.
