### ISSUE TITLE
notify user of delay

### ISSUE THREAD

**Issue by anarcat** [naelstrof/maim#75]
i love the maim and slop combination. unfortunately, I had to create this ugly hack to implement a delay instead of just using `--delay`option because i want feedback to the user that the screenshot is about to be taken...

```
eval $(slop --nodecorations)
notify-send --expire-time=1000 "taking screenshot in 3 secs"; sleep 1
notify-send --expire-time=1000 "taking screenshot in 2 secs"; sleep 1
notify-send --expire-time=900 "taking screenshot in 1 secs"; sleep 1
maim -g $G "$snapsdir/$snap"
```

i'd prefer to use `maim --select --delay 3`, but then there's no visual indication that the screenshot is about to be taken... 

could we have some sort of "CHEEEEEEEESE" visual output before actually taking the screenshot with `--delay`?

thanks!

**Comment by naelstrof** [comment]
Done, https://github.com/naelstrof/maim/commit/3c7348e393c3177da647669a82cf327dd3b63cae
