### ISSUE TITLE
Window IDs from xdotool not accepted

### ISSUE THREAD

**Issue by Streetwalrus** [naelstrof/maim#77]
I've had that happen before, then the issue was somehow solved but it looks like it came back in the new version.

`maim -i $(xdotool getactivewindow)` errors like so:
```
X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  3 (X_GetWindowAttributes)
  Resource id in failed request:  0x3e00008
  Serial number of failed request:  14
  Current serial number in output stream:  15
```

It looks like xdotool and xwininfo return a different ID than slop does, which makes the tools completely incompatible. Also this ID shown in the output is actually 2 less than the input value.

**Comment by naelstrof** [comment]
Could you tell me the desktop environment you're using?

**Comment by Streetwalrus** [comment]
Just i3 on arch.

**Comment by naelstrof** [comment]
I realize maim was working as intended (besides the crashing part).
i3 is reporting a 1x1-1-1 window as the active window within the real window. Each window has one of these secret windows hidden within it.
You can find these relationships with `xwininfo -children`

I added some logic to detect this, and it attempts to select the parent of such windows. Hopefully this won't cause bugs on other systems.

**Comment by Streetwalrus** [comment]
Just tried the latest version, still no luck. `slop -f %i` gives me something like 14680245, while `xdotool getactivewindow` returns 50331658 which is in a completely different range. I've also checked `xwininfo -children`, which returns consistent results with xdotool.

It looks like `slop -n` returns the same ID as xdotool. `maim -n` works fine, but passing that ID still fails.
