### ISSUE TITLE
Segmentation fault when format is specified

### ISSUE THREAD

**Issue by mikroskeem** [naelstrof/maim#81]
When I specify format (`--format png` in my case, had that there from version `3.4.47`), then maim segfaults. When I remove `--format`, maim doesn't segfault.

Only tested with whole screen (1 monitor) and `-s` screenshot.

**Comment by zestyr** [comment]
Maim definitely shouldn't segfault because of that, but the correct syntax is `--format=png`

**Comment by mikroskeem** [comment]
I bet on argument parser issue, but [it does segfault](https://0x0.st/JeQ.png)

Using Arch Linux package, if this helps

**Comment by naelstrof** [comment]
Ah yeah, that's been fixed already. I noticed last night, it is indeed a parser issue. It now properly prints an error message.

You can install slop-git and maim-git from the AUR to fix this now, or wait for the arch linux devs to update the package themselves.

**Comment by mikroskeem** [comment]
So... issue closed I guess?

**Comment by naelstrof** [comment]
Yeah.
