### ISSUE TITLE
Failed to grab keyboard

### ISSUE THREAD

**Issue by Flat** [naelstrof/maim#83]
When calling maim through a keyboard shortcut maim outputs `Failed to grab keyboard.` the script used is `maim -s /path/to/image.png` adding the `-k` flag makes no difference.

**Comment by tudurom** [comment]
I'm getting this too. It started after I updated to the selection fix.

**Comment by naelstrof** [comment]
Could you `git pull`, `make clean`, and `make && sudo make install` in slop, then maim in order. Then try again?
If it happens could you tell me your DE, WM, or which application you're keybinding? I currently cannot replicate the issue.

Currently I believe it's impossible for that message to show up without having an out-of-date slop.
The only piece of code that is could output that is currently commented out, and isn't exactly the same: https://github.com/naelstrof/slop/blob/master/src/keyboard.cpp#L54

**Comment by Flat** [comment]
Looks like it was indeed the result of an out of date slop. Looks like Arch Linux hasn't updated from `5.8.28` yet. https://www.archlinux.org/packages/community/x86_64/slop/

Everything works fine using the master branch of both repositories.
