### ISSUE TITLE
Argument parsing has decayed

### ISSUE THREAD

**Issue by ScoreUnder** [naelstrof/maim#84]
Tested on 4.4.50.

Originally, my most common invocation of `maim` was as:

```
maim -sc 1,0,0,0.8 --hidecursor -- image.png
```

Now, `maim`'s argument parser has lost support for the `--` argument as well as compounded single-letter arguments. See guidelines 5 and 10 on the POSIX utility conventions document: http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap12.html

While that document is focused on the implementation of POSIX utilities and thus technically out of scope, I believe it does give a reasonable approximation of what people expect from a command line application's behaviour, and thus a mostly useful checklist when writing command line applications.

----

Additionally, `maim` now aborts with a `std::logic_error` when an argument's option is missing:
```
score@kirisame ~ % maim -n
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_M_construct null not valid
[1]    5019 abort (core dumped)  maim -n
134 score@kirisame ~ % maim -c
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_M_construct null not valid
[1]    5935 abort (core dumped)  maim -c
134 score@kirisame ~ % maim -r
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_M_construct null not valid
[1]    5976 abort (core dumped)  maim -r
134 score@kirisame ~ % 
```

**Comment by naelstrof** [comment]
Had a feeling this would show up, I can't replicate the crashing, but the decayed argument parsing I'm planning on fixing.

I might just switch over to using [docopt](https://github.com/docopt/docopt.cpp) so I don't have to worry about it.

**Comment by naelstrof** [comment]
Should be fixed with https://github.com/naelstrof/maim/commit/798af2c9fcad6afda7ea5fe5b6d5f7219b39ffa5
slop is soon to follow.

**Comment by naelstrof** [comment]
Been fixed for a while now, slop is too.
