### ISSUE TITLE
i3 keybind + sh `-s` won't work any more

### ISSUE THREAD

**Issue by oliveagle** [naelstrof/maim#85]
Archlinux + i3wm

```bash
#~/.i3/config
bindsym Mod1+Control+a exec --no-startup-id $HOME/bin/maimxclip.sh
```
which means `Ctrl + Alt + a` will execute `~/bin/maimxclip.sh`

```bash
# ~/bin/maimxclip.sh
maim -s -c 1,0,0,0.6 -p 1 --format=png /dev/stdout | xclip -selection clipboard -t image/png -i 
```

Yesterday. I did a full system update. `pacman -Syu`.  now I find out `-s` of maim won't work any more with i3 keybind.

this works
```
#!/bin/sh
maim /tmp/test.png
```

### this won't work
```
#!/bin/sh
maim -s
# the following log works. 
echo "hahah" >> /var/log/haha.log  
```

**Comment by oliveagle** [comment]
... 

`scrot -s` won't work neither.  maybe it's i3wm problem..

**Comment by naelstrof** [comment]
It's not an i3 problem. It is maim _and_ scrots fault. It's been fixed recently: https://github.com/naelstrof/maim/issues/83

Either wait for arch to upgrade their repos, or install slop-git then maim-git from the AUR.
