### ISSUE TITLE
Conflict with compositor

### ISSUE THREAD

**Issue by 676339784** [naelstrof/maim#88]
For me, `maim -s` does not work when `compton` is also running. [What it looks like](https://ptpb.pw/dVeh.png). Otherwise it works perfectly fine. Running `maim` by itself while `compton` is running works fine too.

On v4.4.60

**Comment by naelstrof** [comment]
Disable OpenGL, it should detect this problem though and automatically disable OpenGL. I'll get on it.

**Comment by ahxxm** [comment]
Even with `--noopengl` option, segmentation fault appear randomly.

I'm using i3wm, Windows that are opened are 2: Chromium on left side, 60% of screen, xfce4-terminal takes the right 40%. My screenshot shortcut command is `maim --noopengl --select --format=png /dev/stdout | xclip -selection clipboard -t image/png -i`, which takes screenshot of selected area to clipboard.

GDB tells me it happens in `#0  0x0000000000406bf3 in ARGBImage::blendCursor(X11*) ()`, here's coredump info: [http://pastebin.com/wZ7tJnAg](http://pastebin.com/wZ7tJnAg)  (not sure this can be reproduced in your machine though..)

**Comment by naelstrof** [comment]
What maim version are you using?

**Comment by Brottweiler** [comment]
I reported this as a slop issue, not maim, considering maim uses slop? https://github.com/naelstrof/slop/issues/70

I did not try to disable compton though, I will test it when I can.

**Comment by ahxxm** [comment]
mine is 4.4.60

**Comment by ahxxm** [comment]
finally reproducible here: whenever width of selected area is greater than height, it crashes...
