### ISSUE TITLE
Segfault 

### ISSUE THREAD

**Issue by e-anima** [naelstrof/maim#89]
I get segfault whatever i do:
"maim --noopengl -s"
results in segfault

"maim -v" is 4.4.60

any ideas?

**Comment by zestyr** [comment]
Can't replicate. Try updating to 4.4.61

**Comment by carnager** [comment]
i also get segfaults, but they are not reproducible and happen more or less randomly since latest update

**Comment by naelstrof** [comment]
I can't replicate either, try upgrading to 4.4.61.

**Comment by vatula** [comment]
I get segfaults on maim-5.4.63-1
Consistently, all the time.
[1]    4144 segmentation fault (core dumped)  maim
---
OS: Arch Linux x86_64
Kernel: 4.11.7-1-ARCH 
NVidia proprietary (384.47-1)

**Comment by vatula** [comment]
For me issue was resolved after switching from maim to maim-git package
