### ISSUE TITLE
maim prints to stdout by default now?

### ISSUE THREAD

**Issue by parkerlreed** [naelstrof/maim#90]
I just did a fresh Arch install on a new SSD and have noticed running maim by itself seemingly did nothing at first. Then tested in a terminal and it's printing the raw png data to stdout. Is there a flag for the old behavior?

**Comment by fkmclane** [comment]
There is no longer a flag for that, but you can still get that behavior by using "maim ~/$(date +%s).png" in a Bourne compatible shell. Personally, I just have "main ~/tmp/screenshot.png" in my sxhkd keybindings.

**Comment by parkerlreed** [comment]
Ahh thanks!

**Comment by blueyed** [comment]
I think it is distracting and not helpful to spit binary output to stdout, which is _connected to a terminal_.
There should either be a warning/error in that case, or the old behaviour (which is to write to some file I assume?) should get used automatically.

**Comment by blueyed** [comment]
Side note: even curl does not output binary data to stdout by default anymore: https://github.com/curl/curl/commit/5385450afd61328e7d24b50eeffc2b1571cd9e2f.
