### ISSUE TITLE
Complains about image format even though --format=png is given

### ISSUE THREAD

**Issue by trygveaa** [naelstrof/maim#92]
I'm trying to run this command:

    maim --format=png /tmp/tmp.McsBsj5PWE

And get this error:

    Maim encountered an error:
    Unknown format type: `McsBsj5PWE`, only `png` or `jpg` is allowed.

If `--format` is given, it shouldn't try to guess the format from the file name.

From a brief glanse at the commits, seems like the issue might be that `formatGiven` in `main.cpp` is never set.

**Comment by naelstrof** [comment]
Should be fixed with the new build.
