### ISSUE TITLE
Slop encountered an error:Invalid argument `-g`.

### ISSUE THREAD

**Issue by heelsleeh** [naelstrof/maim#93]
installed slop and miam from source code.
i get below error when i type "maim -s"

No file specified, using /usr/src/maim/slop/1491553610.png
Slop encountered an error:
Invalid argument `-g`.
Selection was cancelled or slop failed to run. Make sure it's installed!

**Comment by naelstrof** [comment]
Maim needs to be updated.

**Comment by naelstrof** [comment]
I realize my comment was a tad ambiguous.

You need to update maim, the new maim uses slop as a library.

**Comment by heelsleeh** [comment]
thanks , i updated them to git, works fine now.
