### ISSUE TITLE
Can't make a screenshot when using the --quality option

### ISSUE THREAD

**Issue by Kyuzial** [naelstrof/maim#95]
Hi,
I have errors when using the quality option, but when using -m it works.
I tried --quality=5, --quality = 5 and --quality 5, always the same result.
![test](https://cloud.githubusercontent.com/assets/9301111/24978153/e9666770-1fcf-11e7-85a6-a9aa403002b0.png)

maim 4.4.62, Archlinux
Thanks

**Comment by naelstrof** [comment]
Oh man, that's pretty bad.
I'm planning on replacing all of the parameter parsing code in the next release. This will probably happen after finals.

**Comment by naelstrof** [comment]
Check out the new tag: https://github.com/naelstrof/maim/releases/tag/v5.4.62

It should be fixed with this commit: https://github.com/naelstrof/maim/commit/798af2c9fcad6afda7ea5fe5b6d5f7219b39ffa5
