### ISSUE TITLE
Package GLX not found when installing on Ubuntu 16.10 (Yakkety)

### ISSUE THREAD

**Issue by lieuzhenghong** [naelstrof/maim#96]
After installing `libxfixes-dev` and `libxrandr-dev`, as well as consulting #76  (installed `libpng12-dev` `libglm-dev` `libjpeg-dev`), I still get the following error:

`CMake Error at /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find GLX (missing: GLX_INCLUDE_DIR GLX_LIBRARY)
`

`Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  modules/FindGLX.cmake:36 (find_package_handle_standard_args)
  CMakeLists.txt:58 (find_package)
`

I am not able to find "GLX" as a package on the Ubuntu repository. Wonder if someone can point me in the right direction...

**Comment by naelstrof** [comment]
A quick search for Ubuntu glx packages gave me these results: http://packages.ubuntu.com/search?keywords=glx

Have you tried installing libgl1-mesa-glx ?

**Comment by lieuzhenghong** [comment]
@naelstrof Thanks for the quick response.

`libgl1-mesa-glx` is a default Ubuntu package. It doesn't need to be installed.

**Comment by naelstrof** [comment]
You just need GLX headers, and libraries. 
`libgl1-mesa-dev` appears to include them, but I don't use Ubuntu so I can't be sure! sorry.

**Comment by lieuzhenghong** [comment]
Hi @naelstrof,

I can confirm that installing `libgl1-mesa-dev` and all its dependencies fixes the issue. Thank you.
