### ISSUE TITLE
Expected `=` after nodecorations

### ISSUE THREAD

**Issue by CyberShadow** [naelstrof/maim#98]
This command line used to work:

```
maim --select --nodecorations=1 --format=png /dev/stdout
```

I remember needing to change `--nodecorations` to `--nodecorations=1` after another breaking change in command-line syntax.

Now, it results in a nonsensical error:

```
Maim encountered an error:
Expected `=` after nodecorations
```

Clearly, there already is a `=` after `nodecorations`.

Using simply `--nodecorations` (without `=1`) again seems to work.

**Comment by naelstrof** [comment]
This will be fixed in the next version, for now just use the shortened version `-n1`

**Comment by naelstrof** [comment]
Fixed. ef4347d127f170a906db93a8129758da00c5fb8e
