### ISSUE TITLE
When compton is running, `maim -s` fails.

### ISSUE THREAD

**Issue by crocket** [naelstrof/maim#99]
compton : https://github.com/chjj/compton/commit/b7f43ee67a1d2d08239a2eb67b7f50fe51a592a8
maim : 4.4.62
Operating System : Gentoo Linux
Desktop Environment : Compton + XMonad + XMobar + Stalonetray

~/.compton.conf

```
detect-client-leader = true;
detect-transient = true;
shadow = true;
shadow-radius = 1;
shadow-offset-x = 1;
shadow-offset-y = 1;
shadow-opacity = 0.3;
fading = true;
fade-delta = 10;
fade-in-step = 0.06;
fade-out-step = 0.08;
vsync = "none";
backend = "xrender";
xinerama-shadow-drop = true;
```

```
$ maim -s ok.png
Maim encountered an error:
OpenGL threw an error: INVALID_ENUM
```

The choice of backend doesn't change the outcome of `maim -s`.
I tried both `xrender` backend and `glx` backend.

`maim -s -o` works around the issue, but if I grab a region with `maim -s -o`, the captured image is too dark to be useful for anything. Look at the following image.

![ok](https://cloud.githubusercontent.com/assets/748856/25385836/3734fbc6-2a00-11e7-9ae3-9f6e625820b0.png)

Grabbing a non-root window with `maim -s -o` doesn't result in darkening.

**Comment by naelstrof** [comment]
I can't easily fix the OpenGL issue, however for the "darkening" issue: have you tried adding "slop" to the exclusion list for compton?
Check out the similar issue here:
https://github.com/naelstrof/maim/issues/54

**Comment by crocket** [comment]
I confirmed that I can work around the issue with either `shadow = false;` or `shadow-exclude = ["class_g = 'slop'"]` in `~/.compton.conf`.

**Comment by naelstrof** [comment]
As for the OpenGL issue, what is your graphics adapter, and graphics drivers?

**Comment by crocket** [comment]
I use AMD Radeon HD6450, and I use `radeon` kernel driver with `xf86-video-ati`.

**Comment by naelstrof** [comment]
Could you try the new slop and maim to see if you still get the OpenGL error?
I've simplified the renderer and lowered the GLSL requirement.

**Comment by naelstrof** [comment]
I reduced the default quality in this commit: 31bb900cb1639257d9d3709199a548bb5fdedf47
People should notice it less now.

**Comment by crocket** [comment]
After I installed `slop-6.3.40` and `maim-5.4.63`, I got the following error.

```
$ maim -s ok.png
Maim encountered an error:
OpenGL threw an error: INVALID_ENUM
```

**Comment by naelstrof** [comment]
Could you give me the output of `glxinfo`?

glxinfo is in the mesa-utils package on most distributions.

**Comment by crocket** [comment]
Here

[glxinfo.txt](https://github.com/naelstrof/maim/files/1043229/glxinfo.txt)

**Comment by daltomi** [comment]
Same problem with slop.

``` bash
./slop  -v
v6.3.45
```

OpenGL:

```
glxinfo | grep version

server glx version string: 1.4
client glx version string: 1.4
GLX version: 1.4
    Max core profile version: 0.0
    Max compat profile version: 2.1
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 2.0
OpenGL version string: 2.1 Mesa 17.1.2
OpenGL shading language version string: 1.20
OpenGL ES profile version string: OpenGL ES 2.0 Mesa 17.1.2
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 1.0.16
```


Debug (fish shell):

```
env MESA_DEBUG=1 ./slop 
Mesa: User error: GL_INVALID_ENUM in glGetIntegerv(pname=GL_NUM_EXTENSIONS)
Slop encountered an error:
OpenGL threw an error: INVALID_ENUM
```

Success:

```
env MESA_GL_VERSION_OVERRIDE="3.0" ./slop 
311x161+423+436

https://www.mesa3d.org/envvars.html

**Comment by naelstrof** [comment]
That's odd that the override causes it to work, I'm specifically asking for OpenGL 3.0 (since that's when they introduced framebuffers into core), and it seems as though your systems don't support OpenGL 3.0.
(according to the glxinfo anyway `OpenGL version string: 2.1 Mesa 17.1.2`)

I don't have any machines with AMD cards, and I don't have any friends who have AMD either. So this bug isn't going to be fixed by me in the foreseeable future.

**Comment by naelstrof** [comment]
Ok I did get my hands on a machine with an AMD card, but I'm guessing it was too modern, or the open-source drivers don't have this issue because slop and maim ran great.

**Comment by crocket** [comment]
You didn't mention that you released `slop-6.3.41`.  `slop-6.3.41` was installed automatically during gentoo upgrade. With `slop-6.3.41`, `maim -s` seems to work.

**Comment by naelstrof** [comment]
Oh good, it isn't working correctly for daltomi though. I'll leave this open.
@daltomi could you tell me what graphics card, desktop environment, and graphics drivers you're using?

**Comment by jcjordyn130** [comment]
Does it happen with any other screenshotting utilities?

**Comment by naelstrof** [comment]
Pretty sure this is fixed.

**Comment by philippludwig** [comment]
It is not, I am experiencing this with version 5.6.3. It would be nice if you could tell us the window class of maim so we can add a shadow exclude rule to picom.

**Comment by philippludwig** [comment]
Nevermind, the real solution is to compile `slop` with opengl support.
